{
  "openapi": "3.0.3",
  "info": {
    "version": "0.8.1",
    "title": "Supaglue Engagement API",
    "contact": {
      "name": "Supaglue",
      "email": "docs@supaglue.com",
      "url": "https://supaglue.com"
    },
    "description": "# Introduction\n\nWelcome to the Supaglue unified Engagement API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.\n\n### Base API URL\n\n```\nhttp://localhost:8080/engagement/v1\n```\n"
  },
  "externalDocs": {
    "description": "Try out our API in Postman!",
    "url": "https://www.postman.com/supaglue/workspace/supaglue-public/overview"
  },
  "servers": [
    {
      "url": "http://localhost:8080/engagement/v1",
      "description": "Local Supaglue API"
    }
  ],
  "paths": {
    "/passthrough": {
      "post": {
        "operationId": "sendPassthroughRequest",
        "tags": [
          "Passthrough"
        ],
        "summary": "Send passthrough request",
        "description": "Send request directly to a provider",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "path": {
                    "type": "string",
                    "description": "The path to send the request to (do not pass the domain)"
                  },
                  "method": {
                    "type": "string",
                    "enum": [
                      "GET",
                      "POST",
                      "PUT",
                      "PATCH",
                      "DELETE"
                    ],
                    "example": "GET"
                  },
                  "headers": {
                    "type": "object",
                    "description": "Headers to pass to downstream",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "query": {
                    "type": "object",
                    "description": "Query parameters to pass to downstream",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "body": {
                    "type": "string",
                    "description": "Body to pass to downstream"
                  }
                },
                "required": [
                  "path",
                  "method"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Passthrough response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "url": {
                      "type": "string",
                      "description": "The full URL the request was went to",
                      "example": "https://customengagement.com/api/cars"
                    },
                    "status": {
                      "type": "number",
                      "description": "Status code from the downstream",
                      "example": 200
                    },
                    "headers": {
                      "type": "object",
                      "description": "The response headers from the downstream",
                      "additionalProperties": {
                        "type": "string"
                      }
                    },
                    "body": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "number"
                        },
                        {
                          "type": "integer"
                        },
                        {
                          "type": "boolean"
                        },
                        {
                          "type": "array",
                          "items": {
                            "additionalProperties": true
                          }
                        },
                        {
                          "type": "object",
                          "additionalProperties": true
                        }
                      ],
                      "description": "The body from the downstream"
                    }
                  },
                  "required": [
                    "url",
                    "status",
                    "headers"
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "url": "https://customengagement.com/api/cars",
                      "status": 200,
                      "headers": {
                        "x-requests-limit": 96
                      },
                      "body": []
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/contacts": {
      "get": {
        "operationId": "getContacts",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "List contacts",
        "description": "Get a list of contacts",
        "parameters": [
          {
            "$ref": "#/components/parameters/include_deleted_data"
          },
          {
            "$ref": "#/components/parameters/include_raw_data"
          },
          {
            "$ref": "#/components/parameters/created_after"
          },
          {
            "$ref": "#/components/parameters/created_before"
          },
          {
            "$ref": "#/components/parameters/modified_after"
          },
          {
            "$ref": "#/components/parameters/modified_before"
          },
          {
            "$ref": "#/components/parameters/cursor"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ],
        "responses": {
          "200": {
            "description": "Contacts",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/pagination"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "results": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/contact"
                          }
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "next": "eyJpZCI6IjEyYjU3ZTM0LWZkMjEtNDk1OS04ZGIwLTA5N2EzZGEzODg2YyIsInJldmVyc2UiOmZhbHNlfQ==",
                      "previous": "eyJpZCI6IjBjZDhmYmZkLWU5NmQtNDEwZC05ZjQxLWIwMjU1YjdmNGI4NyIsInJldmVyc2UiOnRydWV9",
                      "results": [
                        {
                          "id": "4dec71a1-e789-4006-84fe-1a797202dddb",
                          "address": {
                            "city": "San Francisco",
                            "country": "USA",
                            "street_1": "525 Brannan St",
                            "street_2": null,
                            "postalCode": "94107",
                            "state": "CA"
                          },
                          "email_addresses": [
                            {
                              "email_address": "hello@supaglue.com",
                              "email_address_type": "workline2"
                            }
                          ],
                          "first_name": "George",
                          "remote_id": 1234,
                          "last_name": "Xing",
                          "phone_numbers": [
                            {
                              "phone_number": "+14151234567",
                              "phone_number_type": "mobile"
                            }
                          ],
                          "remote_created_at": "2023-02-27T00:00:00Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "createContact",
        "summary": "Create contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_contact"
                  }
                },
                "required": [
                  "model"
                ]
              },
              "example": {
                "model": {
                  "id": "ed7ce0f0-8119-4b73-bf01-4e8e0296ef80",
                  "address": {
                    "city": "San Francisco",
                    "country": "USA",
                    "street_1": "525 Brannan St",
                    "street_2": null,
                    "postalCode": "94107",
                    "state": "CA"
                  },
                  "email_addresses": [
                    {
                      "email_address": "hello@supaglue.com",
                      "email_address_type": "workline2"
                    }
                  ],
                  "first_name": "George",
                  "remote_id": 1234,
                  "last_name": "Xing",
                  "phone_numbers": [
                    {
                      "phone_number": "+14151234567",
                      "phone_number_type": "mobile"
                    }
                  ],
                  "remote_created_at": "2023-02-27T00:00:00Z"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Contact created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/contact"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/contacts/{contact_id}": {
      "get": {
        "operationId": "getContact",
        "summary": "Get contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/include_raw_data"
          }
        ],
        "responses": {
          "200": {
            "description": "Contact",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/contact"
                }
              }
            }
          }
        }
      },
      "patch": {
        "operationId": "updateContact",
        "summary": "Update contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_contact"
                  }
                },
                "required": [
                  "model"
                ]
              },
              "examples": {
                "Example": {
                  "value": {
                    "model": {
                      "id": "6c018f45-f584-4ba8-b1a8-658bb29d300e",
                      "address": {
                        "city": "San Francisco",
                        "country": "USA",
                        "street_1": "525 Brannan St",
                        "street_2": null,
                        "postalCode": "94107",
                        "state": "CA"
                      },
                      "email_addresses": [
                        {
                          "email_address": "hello@supaglue.com",
                          "email_address_type": "workline2"
                        }
                      ],
                      "first_name": "George",
                      "remote_id": 1234,
                      "last_name": "Xing",
                      "phone_numbers": [
                        {
                          "phone_number": "+14151234567",
                          "phone_number_type": "mobile"
                        }
                      ],
                      "remote_created_at": "2023-02-27T00:00:00Z"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Contact updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/contact"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "contact_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/users": {
      "get": {
        "operationId": "getUsers",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "List users",
        "description": "Get a list of users",
        "parameters": [
          {
            "$ref": "#/components/parameters/include_deleted_data"
          },
          {
            "$ref": "#/components/parameters/include_raw_data"
          },
          {
            "$ref": "#/components/parameters/created_after"
          },
          {
            "$ref": "#/components/parameters/created_before"
          },
          {
            "$ref": "#/components/parameters/modified_after"
          },
          {
            "$ref": "#/components/parameters/modified_before"
          },
          {
            "$ref": "#/components/parameters/cursor"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ],
        "responses": {
          "200": {
            "description": "Users",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/pagination"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "results": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/user"
                          }
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "next": "eyJpZCI6IjEyYjU3ZTM0LWZkMjEtNDk1OS04ZGIwLTA5N2EzZGEzODg2YyIsInJldmVyc2UiOmZhbHNlfQ==",
                      "previous": "eyJpZCI6IjBjZDhmYmZkLWU5NmQtNDEwZC05ZjQxLWIwMjU1YjdmNGI4NyIsInJldmVyc2UiOnRydWV9",
                      "results": [
                        {
                          "id": "9572d08b-f19f-48cc-a992-1eb7031d3f6a",
                          "remote_id": 1234,
                          "first_name": "George",
                          "last_name": "Xing",
                          "email": "george@supaglue.com",
                          "remote_created_at": "2021-11-10T00:00:00Z",
                          "remote_updated_at": "2022-01-09T00:00:00Z"
                        },
                        {
                          "id": "a0f8385c-4947-41d2-a276-740f792bb0e6",
                          "remote_id": 1235,
                          "first_name": "Thomas",
                          "last_name": "Chen",
                          "email": "tom@supaglue.com",
                          "remote_created_at": "2021-11-10T00:00:00Z",
                          "remote_updated_at": "2022-01-09T00:00:00Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/users/{user_id}": {
      "get": {
        "operationId": "getUser",
        "summary": "Get user",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/include_raw_data"
          }
        ],
        "responses": {
          "200": {
            "description": "User",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "user_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/mailboxes": {
      "get": {
        "operationId": "getMailboxes",
        "tags": [
          "Mailboxes"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "List mailboxes",
        "description": "Get a list of mailboxes",
        "parameters": [
          {
            "$ref": "#/components/parameters/include_deleted_data"
          },
          {
            "$ref": "#/components/parameters/include_raw_data"
          },
          {
            "$ref": "#/components/parameters/created_after"
          },
          {
            "$ref": "#/components/parameters/created_before"
          },
          {
            "$ref": "#/components/parameters/modified_after"
          },
          {
            "$ref": "#/components/parameters/modified_before"
          },
          {
            "$ref": "#/components/parameters/cursor"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ],
        "responses": {
          "200": {
            "description": "Mailboxes",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/pagination"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "results": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/mailbox"
                          }
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "next": "eyJpZCI6IjEyYjU3ZTM0LWZkMjEtNDk1OS04ZGIwLTA5N2EzZGEzODg2YyIsInJldmVyc2UiOmZhbHNlfQ==",
                      "previous": "eyJpZCI6IjBjZDhmYmZkLWU5NmQtNDEwZC05ZjQxLWIwMjU1YjdmNGI4NyIsInJldmVyc2UiOnRydWV9",
                      "results": [
                        {
                          "id": "262b99cd-73fa-4bd3-bbc2-baecbd0fa14d",
                          "remote_id": 1234,
                          "email": "george@supaglue.com",
                          "user_id": "fe4d5ef2-6b29-4082-96a3-cfe26e4ff22e",
                          "remote_created_at": "2021-11-10T00:00:00Z",
                          "remote_updated_at": "2022-01-09T00:00:00Z"
                        },
                        {
                          "id": "da2bf8b7-d3fc-410a-81f8-6e7255ad9248",
                          "remote_id": 1235,
                          "email": "tom@supaglue.com",
                          "user_id": "e330814b-77a7-4ca9-9381-19da883593e7",
                          "remote_created_at": "2021-11-10T00:00:00Z",
                          "remote_updated_at": "2022-01-09T00:00:00Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/mailboxes/{mailbox_id}": {
      "get": {
        "operationId": "getMailbox",
        "summary": "Get mailbox",
        "tags": [
          "Mailboxes"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/include_raw_data"
          }
        ],
        "responses": {
          "200": {
            "description": "Mailbox",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/mailbox"
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "mailbox_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/sequences": {
      "get": {
        "operationId": "getSequences",
        "summary": "List sequences",
        "tags": [
          "Sequences"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "description": "Get a list of sequences ",
        "parameters": [
          {
            "$ref": "#/components/parameters/include_deleted_data"
          },
          {
            "$ref": "#/components/parameters/include_raw_data"
          },
          {
            "$ref": "#/components/parameters/created_after"
          },
          {
            "$ref": "#/components/parameters/created_before"
          },
          {
            "$ref": "#/components/parameters/modified_after"
          },
          {
            "$ref": "#/components/parameters/modified_before"
          },
          {
            "$ref": "#/components/parameters/cursor"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ],
        "responses": {
          "200": {
            "description": "Sequences",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/pagination"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "results": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/sequence"
                          }
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "next": "eyJpZCI6IjEyYjU3ZTM0LWZkMjEtNDk1OS04ZGIwLTA5N2EzZGEzODg2YyIsInJldmVyc2UiOmZhbHNlfQ==",
                      "previous": "eyJpZCI6IjBjZDhmYmZkLWU5NmQtNDEwZC05ZjQxLWIwMjU1YjdmNGI4NyIsInJldmVyc2UiOnRydWV9",
                      "results": [
                        {
                          "id": "13bc2a55-be6a-4cb9-8ea3-12dc1e41ac59",
                          "is_enabled": true,
                          "name": "Sample Sequence",
                          "tags": [
                            "tag1",
                            "tag2"
                          ],
                          "num_steps": 5,
                          "schedule_count": 0,
                          "open_count": 0,
                          "opt_out_count": 0,
                          "reply_count": 0,
                          "click_count": 0,
                          "remote_created_at": "2023-02-27T00:00:00Z",
                          "remote_updated_at": "2023-02-27T00:00:00Z",
                          "last_modified": "2023-02-27T00:00:00Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/sequences/{sequence_id}": {
      "get": {
        "operationId": "getSequence",
        "summary": "Get sequence",
        "tags": [
          "Sequences"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/include_raw_data"
          }
        ],
        "responses": {
          "200": {
            "description": "Sequence",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/sequence"
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "sequence_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/sequence_states": {
      "get": {
        "operationId": "getSequenceStates",
        "tags": [
          "SequenceStates"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "summary": "List mailboxes",
        "description": "Get a list of mailboxes",
        "parameters": [
          {
            "$ref": "#/components/parameters/include_deleted_data"
          },
          {
            "$ref": "#/components/parameters/include_raw_data"
          },
          {
            "$ref": "#/components/parameters/created_after"
          },
          {
            "$ref": "#/components/parameters/created_before"
          },
          {
            "$ref": "#/components/parameters/modified_after"
          },
          {
            "$ref": "#/components/parameters/modified_before"
          },
          {
            "$ref": "#/components/parameters/cursor"
          },
          {
            "$ref": "#/components/parameters/page_size"
          }
        ],
        "responses": {
          "200": {
            "description": "Sequence States",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/pagination"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "results": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/sequence_state"
                          }
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "next": "eyJpZCI6IjEyYjU3ZTM0LWZkMjEtNDk1OS04ZGIwLTA5N2EzZGEzODg2YyIsInJldmVyc2UiOmZhbHNlfQ==",
                      "previous": "eyJpZCI6IjBjZDhmYmZkLWU5NmQtNDEwZC05ZjQxLWIwMjU1YjdmNGI4NyIsInJldmVyc2UiOnRydWV9",
                      "results": [
                        {
                          "id": "6bf506a8-0a5a-419a-bd24-32b4a66d5db5",
                          "remote_id": 1234,
                          "state": "active",
                          "mailbox_id": "8308b381-7e78-44d2-a820-74af1c71c6c2",
                          "contact_id": "f3185edb-39d8-4bff-a560-3dbc8bfd8056",
                          "sequence_id": "05660383-6bac-463d-b7d6-b8ebc4cb6e3b",
                          "remote_created_at": "2023-02-27T00:00:00Z",
                          "remote_updated_at": "2023-02-27T00:00:00Z"
                        },
                        {
                          "id": "e86309e9-25f5-4898-904b-7b4ee87a3181",
                          "remote_id": 1235,
                          "mailbox_id": "a379e517-1314-48d5-8ad9-2afb793be11e",
                          "contact_id": "41a71062-48ce-462a-8e53-af77e5df2ac3",
                          "sequence_id": "989146f3-611c-4a55-ae1b-ad83c769b197",
                          "remote_created_at": "2023-02-27T00:00:00Z",
                          "remote_updated_at": "2023-02-27T00:00:00Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "createSequenceState",
        "summary": "Create sequence state",
        "tags": [
          "SequenceState"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_sequence_state"
                  }
                },
                "required": [
                  "model"
                ]
              },
              "example": {
                "model": {
                  "id": "355843a5-c536-4e82-b497-05160bfb7d78",
                  "state": "active",
                  "mailbox_id": "a7e860b5-cb8b-400b-812d-921fa526140c",
                  "contact_id": "6bdcebc2-f886-4de3-88ed-0b9eb420f7b1",
                  "sequence_id": "45e07817-fd59-4ec8-a727-066d2db27c9b",
                  "remote_created_at": "2023-02-27T00:00:00Z",
                  "remote_updated_at": "2023-02-27T00:00:00Z"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sequence state created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/sequence_state"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/sequence_states/{sequence_state_id}": {
      "get": {
        "operationId": "getSequenceState",
        "summary": "Get sequence state",
        "tags": [
          "Sequence States"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/include_raw_data"
          }
        ],
        "responses": {
          "200": {
            "description": "Sequence State",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/sequence_state"
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "sequence_state_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "ffb62704-addd-454e-bb86-ed0799703dc6"
          }
        }
      ]
    }
  },
  "tags": [
    {
      "name": "Contacts",
      "description": "The `Contact` Common Model is used to represent a \"contact\" in Engagements."
    },
    {
      "name": "Sequences",
      "description": "The `Sequence` Common Model is used to represent a \"sequence\" in Engagements."
    },
    {
      "name": "Sequence States",
      "description": "The `Sequence State` Common Model is used to represent the state of a contact in a sequence."
    },
    {
      "name": "Users",
      "description": "The `User` Common Model is used to represent a \"user\" in Engagements."
    },
    {
      "name": "Mailboxes",
      "description": "The `Mailbox` Common Model is used to represent email mailbox, used within the application for sending and syncing emails"
    },
    {
      "name": "Passthrough",
      "description": "Passthrough operations to underlying providers."
    }
  ],
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "name": "x-api-key",
        "in": "header",
        "description": "API key to allow developers to access the API"
      }
    },
    "schemas": {
      "contact": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "4cee77aa-50ae-4369-be1e-03f15a55ef10"
          },
          "remote_id": {
            "type": "string",
            "example": 54312
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "23e640fe-6105-4a11-a636-3aa6b6c6e762"
          },
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "job_title": {
            "type": "string",
            "nullable": true,
            "example": "CEO"
          },
          "address": {
            "$ref": "#/components/schemas/address"
          },
          "email_addresses": {
            "$ref": "#/components/schemas/email_addresses"
          },
          "phone_numbers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "phone_number": {
                  "type": "string",
                  "nullable": true,
                  "example": "+14151234567"
                },
                "phone_number_type": {
                  "type": "string",
                  "nullable": true,
                  "enum": [
                    "work",
                    "home",
                    "mobile",
                    "other"
                  ]
                }
              },
              "required": [
                "phone_number",
                "phone_number_type"
              ]
            },
            "example": [
              {
                "phone_number": "+14151234567",
                "phone_number_type": "work"
              }
            ]
          },
          "open_count": {
            "type": "number"
          },
          "click_count": {
            "type": "number"
          },
          "reply_count": {
            "type": "number"
          },
          "bounced_count": {
            "type": "number"
          },
          "remote_created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "remote_updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "remote_was_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "raw_data": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "required": [
          "id",
          "remote_id",
          "owner_id",
          "first_name",
          "last_name",
          "job_title",
          "address",
          "email_addresses",
          "phone_numbers",
          "open_count",
          "click_count",
          "reply_count",
          "bounced_count",
          "remote_created_at",
          "remote_updated_at",
          "remote_was_deleted",
          "last_modified_at"
        ]
      },
      "create_contact": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "job_title": {
            "type": "string",
            "nullable": true,
            "example": "CEO"
          },
          "address": {
            "$ref": "#/components/schemas/address"
          },
          "email_addresses": {
            "$ref": "#/components/schemas/email_addresses"
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "9f3e97fd-4d5d-4efc-959d-bbebfac079f5"
          },
          "custom_fields": {
            "$ref": "#/components/schemas/custom_fields"
          }
        }
      },
      "sequence_state": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "e19a7c83-6480-46cc-9ea7-a5b82b30d04b"
          },
          "remote_id": {
            "type": "string",
            "example": 54312
          },
          "state": {
            "type": "string",
            "nullable": true,
            "example": "active"
          },
          "contact_id": {
            "type": "string",
            "nullable": true,
            "example": "c590dc63-8e43-48a4-8154-1fbb00ac936b"
          },
          "mailbox_id": {
            "nullable": true,
            "type": "string",
            "example": "39fd1fe0-094b-4a61-b47f-3e3ac033203d"
          },
          "sequence_id": {
            "nullable": true,
            "type": "string",
            "example": "b854e510-1c40-4ef6-ade4-8eb35f49d331"
          },
          "remote_created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "remote_updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "remote_was_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "remote_id",
          "state",
          "mailbox_id",
          "contact_id",
          "sequence_id",
          "remote_created_at",
          "remote_updated_at",
          "remote_was_deleted",
          "last_modified_at"
        ]
      },
      "create_sequence_state": {
        "type": "object",
        "properties": {
          "contact_id": {
            "type": "string",
            "example": "c590dc63-8e43-48a4-8154-1fbb00ac936b"
          },
          "mailbox_id": {
            "type": "string",
            "example": "39fd1fe0-094b-4a61-b47f-3e3ac033203d"
          },
          "sequence_id": {
            "type": "string",
            "example": "b854e510-1c40-4ef6-ade4-8eb35f49d331"
          }
        },
        "required": [
          "contact_id",
          "mailbox_id",
          "sequence_id"
        ]
      },
      "mailbox": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "e19a7c83-6480-46cc-9ea7-a5b82b30d04b"
          },
          "remote_id": {
            "type": "string",
            "example": 54312
          },
          "email": {
            "type": "string",
            "nullable": true,
            "example": null
          },
          "user_id": {
            "nullable": true,
            "type": "string",
            "example": "39fd1fe0-094b-4a61-b47f-3e3ac033203d"
          },
          "remote_created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "remote_updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "remote_was_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "remote_id",
          "email",
          "user_id",
          "remote_created_at",
          "remote_updated_at",
          "remote_was_deleted",
          "last_modified_at"
        ]
      },
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "e888cedf-e9d0-42c5-9485-2d72984faef2"
          },
          "remote_id": {
            "type": "string",
            "example": 54312
          },
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "email": {
            "type": "string",
            "nullable": true,
            "example": "george@supaglue.com"
          },
          "remote_created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "remote_updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "remote_was_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "remote_id",
          "first_name",
          "last_name",
          "email",
          "remote_created_at",
          "remote_updated_at",
          "remote_was_deleted",
          "last_modified_at"
        ]
      },
      "sequence": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "88588bae-3785-4223-81b7-0649012fdeda"
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "95fe0d29-e8cc-48ac-9afd-e02d8037a597"
          },
          "remote_id": {
            "type": "string",
            "example": 54312
          },
          "is_enabled": {
            "type": "boolean",
            "example": true
          },
          "name": {
            "nullable": true,
            "type": "string"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "num_steps": {
            "type": "number"
          },
          "schedule_count": {
            "type": "number"
          },
          "open_count": {
            "type": "number"
          },
          "opt_out_count": {
            "type": "number"
          },
          "reply_count": {
            "type": "number"
          },
          "click_count": {
            "type": "number"
          },
          "remote_created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "remote_updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "remote_id",
          "is_enabled",
          "name",
          "tags",
          "num_steps",
          "schedule_count",
          "open_count",
          "opt_out_count",
          "reply_count",
          "click_count",
          "remote_created_at",
          "remote_updated_at",
          "last_modified_at"
        ]
      },
      "start_sequence": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "fields": {
            "type": "object",
            "properties": {
              "contact_id": {
                "type": "string"
              },
              "mailbox_id": {
                "type": "string"
              }
            },
            "required": [
              "contact_id",
              "mailbox_id"
            ]
          }
        },
        "required": [
          "id",
          "fields"
        ]
      },
      "pagination": {
        "type": "object",
        "properties": {
          "next": {
            "type": "string",
            "nullable": true,
            "example": "eyJpZCI6IjQyNTc5ZjczLTg1MjQtNDU3MC05YjY3LWVjYmQ3MDJjNmIxNCIsInJldmVyc2UiOmZhbHNlfQ=="
          },
          "previous": {
            "type": "string",
            "nullable": true,
            "example": "eyJpZCI6IjBjZDhmYmZkLWU5NmQtNDEwZC05ZjQxLWIwMjU1YjdmNGI4NyIsInJldmVyc2UiOnRydWV9"
          }
        }
      },
      "address": {
        "type": "object",
        "nullable": true,
        "properties": {
          "city": {
            "type": "string",
            "nullable": true,
            "example": "San Francisco"
          },
          "country": {
            "type": "string",
            "nullable": true,
            "example": "USA"
          },
          "postal_code": {
            "type": "string",
            "nullable": true,
            "example": "94107"
          },
          "state": {
            "type": "string",
            "nullable": true,
            "example": "CA"
          },
          "street_1": {
            "type": "string",
            "nullable": true,
            "example": "525 Brannan"
          },
          "street_2": {
            "type": "string",
            "nullable": true,
            "example": null
          }
        },
        "required": [
          "city",
          "country",
          "postal_code",
          "state",
          "street_1",
          "street_2"
        ],
        "example": [
          {
            "city": "San Francisco",
            "country": "US",
            "postal_code": "94107",
            "state": "CA",
            "street_1": "525 Brannan",
            "street_2": null
          }
        ]
      },
      "email_addresses": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "email_address": {
              "type": "string",
              "example": "hello@supaglue.com"
            },
            "email_address_type": {
              "type": "string",
              "nullable": true,
              "enum": [
                "personal",
                "work"
              ]
            }
          },
          "required": [
            "email_address",
            "email_address_type"
          ]
        },
        "example": [
          {
            "email_address": "hello@supaglue.com",
            "email_address_type": "work"
          }
        ]
      },
      "custom_fields": {
        "type": "object",
        "additionalProperties": true,
        "description": "Custom properties to be inserted that are not covered by the common model. Object keys must match exactly to the corresponding provider API."
      },
      "logs": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "dashboard_view": {
              "type": "string",
              "example": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832"
            },
            "log_id": {
              "type": "string",
              "example": "99433219-8017-4acd-bb3c-ceb23d663832"
            },
            "log_summary": {
              "type": "object",
              "properties": {
                "method": {
                  "type": "string",
                  "example": "POST"
                },
                "status_code": {
                  "type": "number",
                  "example": 200
                },
                "url": {
                  "type": "string",
                  "example": "https://harvest.greenhouse.io/v1/candidates/"
                }
              }
            }
          }
        },
        "example": [
          {
            "dashboard_view": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832",
            "log_id": "99433219-8017-4acd-bb3c-ceb23d663832",
            "log_summary": {
              "method": "POST",
              "status_code": 200,
              "url": "https://harvest.greenhouse.io/v1/candidates/"
            }
          },
          {
            "dashboard_view": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832",
            "log_id": "99433219-8017-4acd-bb3c-ceb23d663832",
            "log_summary": {
              "method": "POST",
              "status_code": 200,
              "url": "https://harvest.greenhouse.io/v1/candidates/"
            }
          }
        ]
      },
      "errors": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "detail": {
              "type": "string",
              "example": "name is a required field on model."
            },
            "problem_type": {
              "type": "string",
              "example": "MISSING_REQUIRED_FIELD"
            },
            "source": {
              "type": "object",
              "properties": {
                "pointer": {
                  "type": "string",
                  "example": "irure consectetur"
                }
              }
            },
            "title": {
              "type": "string",
              "example": "Missing Required Field"
            }
          },
          "example": [
            {
              "detail": "name is a required field on model.",
              "problem_type": "MISSING_REQUIRED_FIELD",
              "source": {
                "pointer": "irure consectetur"
              },
              "title": "Missing Required Field"
            },
            {
              "detail": "name is a required field on model.",
              "problem_type": "MISSING_REQUIRED_FIELD",
              "source": {
                "pointer": "et"
              },
              "title": "Missing Required Field"
            }
          ]
        }
      },
      "warnings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "detail": {
              "type": "string",
              "example": "An unrecognized field, age, was passed in with request data."
            },
            "problem_type": {
              "type": "string",
              "example": "UNRECOGNIZED_FIELD"
            },
            "source": {
              "type": "object",
              "properties": {
                "pointer": {
                  "type": "string",
                  "example": "Lorem ipsum"
                }
              }
            },
            "title": {
              "type": "string",
              "example": "Unrecognized Field"
            }
          }
        },
        "example": [
          {
            "detail": "An unrecognized field, age, was passed in with request data.",
            "problem_type": "UNRECOGNIZED_FIELD",
            "source": {
              "pointer": "Lorem ipsum"
            },
            "title": "Unrecognized Field"
          },
          {
            "detail": "An unrecognized field, age, was passed in with request data.",
            "problem_type": "UNRECOGNIZED_FIELD",
            "source": {
              "pointer": "in"
            },
            "title": "Unrecognized Field"
          }
        ]
      }
    },
    "parameters": {
      "include_deleted_data": {
        "name": "include_deleted_data",
        "in": "query",
        "schema": {
          "type": "boolean",
          "example": true
        },
        "description": "Whether to include data that was deleted in providers."
      },
      "include_raw_data": {
        "name": "include_raw_data",
        "in": "query",
        "schema": {
          "type": "boolean",
          "example": true
        },
        "description": "Whether to include raw data fetched from the 3rd party provider."
      },
      "created_after": {
        "name": "created_after",
        "in": "query",
        "schema": {
          "type": "string",
          "format": "date-time",
          "example": "2023-02-23T00:00:00.000Z"
        },
        "description": "If provided, will only return objects created after this datetime"
      },
      "created_before": {
        "name": "created_before",
        "in": "query",
        "schema": {
          "type": "string",
          "format": "date-time",
          "example": "2023-02-23T00:00:00.000Z"
        },
        "description": "If provided, will only return objects created before this datetime"
      },
      "modified_after": {
        "name": "modified_after",
        "in": "query",
        "schema": {
          "type": "string",
          "format": "date-time",
          "example": "2023-02-23T00:00:00.000Z"
        },
        "description": "If provided, will only return objects modified after this datetime"
      },
      "modified_before": {
        "name": "modified_before",
        "in": "query",
        "schema": {
          "type": "string",
          "format": "date-time",
          "example": "2023-02-23T00:00:00.000Z"
        },
        "description": "If provided, will only return objects modified before this datetime"
      },
      "cursor": {
        "name": "cursor",
        "in": "query",
        "schema": {
          "type": "string",
          "example": "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw"
        },
        "description": "The pagination cursor value"
      },
      "page_size": {
        "name": "page_size",
        "in": "query",
        "schema": {
          "type": "string",
          "example": "3804695"
        },
        "description": "Number of results to return per page"
      },
      "x-customer-id": {
        "name": "x-customer-id",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "my-customer-1"
        },
        "description": "The customer ID that uniquely identifies the customer in your application",
        "required": true
      },
      "x-provider-name": {
        "name": "x-provider-name",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "salesforce"
        },
        "description": "The provider name",
        "required": true
      }
    }
  }
}
