{
  "openapi": "3.0.3",
  "info": {
    "version": "0.7.6",
    "title": "Supaglue CRM API",
    "contact": {
      "name": "Supaglue",
      "email": "docs@supaglue.com",
      "url": "https://supaglue.com"
    },
    "description": "# Introduction\n\nWelcome to the Supaglue unified CRM API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.\n\n### Base API URL\n\n```\nhttp://localhost:8080/crm/v1\n```\n"
  },
  "externalDocs": {
    "description": "Try out our API in Postman!",
    "url": "https://www.postman.com/supaglue/workspace/supaglue-public/overview"
  },
  "servers": [
    {
      "url": "http://localhost:8080/crm/v1",
      "description": "Local Supaglue API"
    }
  ],
  "paths": {
    "/accounts": {
      "post": {
        "operationId": "createAccount",
        "summary": "Create account",
        "tags": [
          "Accounts"
        ],
        "parameters": [],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_update_account"
                  }
                },
                "required": [
                  "model"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Account created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/account"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/accounts/{account_id}": {
      "patch": {
        "operationId": "updateAccount",
        "summary": "Update account",
        "tags": [
          "Accounts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_update_account"
                  }
                },
                "required": [
                  "model"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Account updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/account"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "account_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/contacts": {
      "post": {
        "operationId": "createContact",
        "summary": "Create contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_update_contact"
                  }
                },
                "required": [
                  "model"
                ]
              },
              "example": {
                "model": {
                  "first_name": "George",
                  "last_activity_at": "2022-02-10T00:00:00Z",
                  "last_name": "Xing",
                  "account_id": "64571bff-48ea-4469-9fa0-ee1a0bab38bd"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Contact created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/contact"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/contacts/{contact_id}": {
      "patch": {
        "operationId": "updateContact",
        "summary": "Update contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_update_contact"
                  }
                },
                "required": [
                  "model"
                ]
              },
              "examples": {
                "Example": {
                  "value": {
                    "model": {
                      "first_name": "George",
                      "last_name": "Xing",
                      "account_id": "0ce05511-adbc-4144-a049-6631c7ea3b04"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Contact updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/contact"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "contact_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/leads": {
      "post": {
        "operationId": "createLead",
        "summary": "Create lead",
        "tags": [
          "Leads"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_update_lead"
                  }
                },
                "required": [
                  "model"
                ]
              },
              "example": {
                "model": {
                  "company": "Supaglue",
                  "first_name": "George",
                  "last_name": "Xing",
                  "lead_source": "API Blogger",
                  "title": "Co-Founder"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Lead created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/lead"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/leads/{lead_id}": {
      "patch": {
        "operationId": "updateLead",
        "summary": "Update lead",
        "tags": [
          "Leads"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_update_lead"
                  }
                },
                "required": [
                  "model"
                ]
              },
              "examples": {
                "Example": {
                  "value": {
                    "model": {
                      "company": "Supaglue",
                      "first_name": "George",
                      "last_name": "Xing",
                      "lead_source": "API Blogger",
                      "title": "Co-Founder"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Lead updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/lead"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "lead_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "82de27cb-6f8c-4278-b783-82d1d916eddc"
          }
        }
      ]
    },
    "/events": {
      "post": {
        "operationId": "createEvent",
        "summary": "Create event",
        "tags": [
          "Events"
        ],
        "parameters": [],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_update_event"
                  }
                },
                "required": [
                  "model"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Event created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/event"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/events/{event_id}": {
      "patch": {
        "operationId": "updateEvent",
        "summary": "Update event",
        "tags": [
          "Events"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_update_event"
                  }
                },
                "required": [
                  "model"
                ]
              },
              "examples": {
                "Example": {
                  "value": {
                    "model": {
                      "type": "Meeting",
                      "subject": "Meeting",
                      "content": null,
                      "start_time": "2022-02-27T00:00:00Z",
                      "end_time": "2022-02-27T00:30:00Z",
                      "owner_id": "4593d277-1654-4192-b155-a4663f1dbdc2",
                      "account_id": "0ce05511-adbc-4144-a049-6631c7ea3b04"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Event updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/event"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "event_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/opportunities": {
      "post": {
        "operationId": "createOpportunity",
        "summary": "Create opportunity",
        "tags": [
          "Opportunities"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_update_opportunity"
                  }
                },
                "required": [
                  "model"
                ]
              },
              "example": {
                "model": {
                  "amount": 100000,
                  "close_date": "2023-02-27T00:00:00Z",
                  "description": "Wants to use open source unified API for third-party integrations",
                  "name": "Needs Integrations",
                  "stage": "Closed Won",
                  "account_id": "109c88c0-7bf4-4cd8-afbc-b51f9432ca0b"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Opportunity created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/opportunity"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/opportunities/{opportunity_id}": {
      "patch": {
        "operationId": "updateOpportunity",
        "summary": "Update opportunity",
        "tags": [
          "Opportunities"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_update_opportunity"
                  }
                },
                "required": [
                  "model"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Opportunity updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "model": {
                      "$ref": "#/components/schemas/opportunity"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "opportunity_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "c9f58083-a370-47b5-ad02-99160ea20372"
          }
        }
      ]
    },
    "/passthrough": {
      "post": {
        "operationId": "sendPassthroughRequest",
        "tags": [
          "Passthrough"
        ],
        "summary": "Send passthrough request",
        "description": "Send request directly to a provider",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "path": {
                    "type": "string",
                    "description": "The path to send the request to (do not pass the domain)"
                  },
                  "method": {
                    "type": "string",
                    "enum": [
                      "GET",
                      "POST",
                      "PUT",
                      "PATCH",
                      "DELETE"
                    ],
                    "example": "GET"
                  },
                  "headers": {
                    "type": "object",
                    "description": "Headers to pass to downstream",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "query": {
                    "type": "object",
                    "description": "Query parameters to pass to downstream",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "body": {
                    "type": "string",
                    "description": "Body to pass to downstream"
                  }
                },
                "required": [
                  "path",
                  "method"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Passthrough response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "url": {
                      "type": "string",
                      "description": "The full URL the request was went to",
                      "example": "https://customcrm.com/api/cars"
                    },
                    "status": {
                      "type": "number",
                      "description": "Status code from the downstream",
                      "example": 200
                    },
                    "headers": {
                      "type": "object",
                      "description": "The response headers from the downstream",
                      "additionalProperties": {
                        "type": "string"
                      }
                    },
                    "body": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "number"
                        },
                        {
                          "type": "integer"
                        },
                        {
                          "type": "boolean"
                        },
                        {
                          "type": "array",
                          "items": {
                            "additionalProperties": true
                          }
                        },
                        {
                          "type": "object",
                          "additionalProperties": true
                        }
                      ],
                      "description": "The body from the downstream"
                    }
                  },
                  "required": [
                    "url",
                    "status",
                    "headers"
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "url": "https://customcrm.com/api/cars",
                      "status": 200,
                      "headers": {
                        "x-requests-limit": 96
                      },
                      "body": []
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    }
  },
  "tags": [
    {
      "name": "Accounts",
      "description": "The `Account` Common Model is used to represent a \"company\" in CRMs."
    },
    {
      "name": "Contacts",
      "description": "The `Contact` Common Model is used to represent a \"contact\" in CRMs."
    },
    {
      "name": "Leads",
      "description": "The `Lead` Common Model is used to represent a \"potential customer\" in CRMs."
    },
    {
      "name": "Opportunities",
      "description": "The `Opportunity` Common Model is used to represent a \"deal opportunity\" in CRMs."
    },
    {
      "name": "Users",
      "description": "The `User` Common Model is used to represent a \"user\" that can login to CRMs."
    },
    {
      "name": "Passthrough",
      "description": "Passthrough operations to underlying providers."
    }
  ],
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "name": "x-api-key",
        "in": "header",
        "description": "API key to allow developers to access the API"
      }
    },
    "schemas": {
      "account": {
        "type": "object",
        "properties": {
          "addresses": {
            "$ref": "#/components/schemas/addresses"
          },
          "description": {
            "type": "string",
            "nullable": true,
            "example": "Integration API"
          },
          "id": {
            "type": "string",
            "example": 1234
          },
          "industry": {
            "type": "string",
            "nullable": true,
            "example": "API's"
          },
          "last_activity_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "name": {
            "type": "string",
            "nullable": true,
            "example": "Sample Customer"
          },
          "number_of_employees": {
            "type": "integer",
            "nullable": true,
            "example": 276000
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          },
          "owner": {
            "$ref": "#/components/schemas/user"
          },
          "phone_numbers": {
            "$ref": "#/components/schemas/phone_numbers"
          },
          "lifecycle_stage": {
            "$ref": "#/components/schemas/lifecycle_stage"
          },
          "website": {
            "type": "string",
            "nullable": true,
            "example": "https://supaglue.com/"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "was_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "addresses",
          "description",
          "id",
          "industry",
          "last_activity_at",
          "name",
          "number_of_employees",
          "owner_id",
          "phone_numbers",
          "website",
          "lifecycle_stage",
          "created_at",
          "updated_at",
          "was_deleted",
          "last_modified_at"
        ]
      },
      "create_update_account": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "nullable": true,
            "example": "Integration API"
          },
          "industry": {
            "type": "string",
            "nullable": true,
            "example": "API's"
          },
          "name": {
            "type": "string",
            "nullable": true,
            "example": "Sample Customer"
          },
          "number_of_employees": {
            "type": "integer",
            "nullable": true,
            "example": 276000
          },
          "website": {
            "type": "string",
            "nullable": true,
            "example": "https://supaglue.com/"
          },
          "addresses": {
            "$ref": "#/components/schemas/addresses"
          },
          "phone_numbers": {
            "$ref": "#/components/schemas/phone_numbers"
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "9f3e97fd-4d5d-4efc-959d-bbebfac079f5"
          },
          "lifecycle_stage": {
            "$ref": "#/components/schemas/lifecycle_stage"
          },
          "custom_fields": {
            "$ref": "#/components/schemas/custom_fields"
          }
        }
      },
      "contact": {
        "type": "object",
        "properties": {
          "account_id": {
            "type": "string",
            "nullable": true,
            "example": "fd089246-09b1-4e3b-a60a-7a76314bbcce"
          },
          "account": {
            "$ref": "#/components/schemas/account"
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "23e640fe-6105-4a11-a636-3aa6b6c6e762"
          },
          "owner": {
            "$ref": "#/components/schemas/user"
          },
          "addresses": {
            "$ref": "#/components/schemas/addresses"
          },
          "email_addresses": {
            "$ref": "#/components/schemas/email_addresses"
          },
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "id": {
            "type": "string",
            "example": 54312
          },
          "last_activity_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "phone_numbers": {
            "$ref": "#/components/schemas/phone_numbers"
          },
          "lifecycle_stage": {
            "$ref": "#/components/schemas/lifecycle_stage"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "was_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "account_id",
          "owner_id",
          "description",
          "id",
          "addresses",
          "email_addresses",
          "first_name",
          "last_activity_at",
          "last_name",
          "phone_numbers",
          "lifecycle_stage",
          "created_at",
          "updated_at",
          "was_deleted",
          "last_modified_at"
        ]
      },
      "create_update_contact": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "account_id": {
            "type": "string",
            "nullable": true,
            "example": "64571bff-48ea-4469-9fa0-ee1a0bab38bd"
          },
          "addresses": {
            "$ref": "#/components/schemas/addresses"
          },
          "email_addresses": {
            "$ref": "#/components/schemas/email_addresses"
          },
          "phone_numbers": {
            "$ref": "#/components/schemas/phone_numbers"
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "9f3e97fd-4d5d-4efc-959d-bbebfac079f5"
          },
          "lifecycle_stage": {
            "$ref": "#/components/schemas/lifecycle_stage"
          },
          "custom_fields": {
            "$ref": "#/components/schemas/custom_fields"
          }
        }
      },
      "event": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": 1234
          },
          "type": {
            "type": "string",
            "nullable": true,
            "example": "Meeting"
          },
          "subject": {
            "type": "string",
            "nullable": true,
            "example": "Meeting"
          },
          "start_time": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "end_time": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "content": {
            "type": "string",
            "nullable": true
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          },
          "owner": {
            "$ref": "#/components/schemas/user"
          },
          "account_id": {
            "type": "string",
            "nullable": true,
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          },
          "account": {
            "$ref": "#/components/schemas/account"
          },
          "contact_id": {
            "type": "string",
            "nullable": true,
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          },
          "contact": {
            "$ref": "#/components/schemas/contact"
          },
          "lead_id": {
            "type": "string",
            "nullable": true,
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          },
          "lead": {
            "$ref": "#/components/schemas/lead"
          },
          "opportunity_id": {
            "type": "string",
            "nullable": true,
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          },
          "opportunity": {
            "$ref": "#/components/schemas/opportunity"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "was_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "subject",
          "type",
          "content",
          "start_time",
          "end_time",
          "owner_id",
          "account_id",
          "contact_id",
          "lead_id",
          "opportunity_id",
          "created_at",
          "updated_at",
          "was_deleted",
          "last_modified_at"
        ]
      },
      "create_update_event": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "nullable": true,
            "example": "Meeting"
          },
          "subject": {
            "type": "string",
            "nullable": true,
            "example": "Meeting"
          },
          "start_time": {
            "type": "string",
            "nullable": true,
            "example": "2022-02-27T00:00:00Z"
          },
          "end_time": {
            "type": "string",
            "nullable": true,
            "example": "2022-02-27T00:00:00Z"
          },
          "content": {
            "type": "string",
            "nullable": true
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          },
          "account_id": {
            "type": "string",
            "nullable": true,
            "example": "1393711e-b7ba-46ef-b9cd-49134cf2c630"
          },
          "contact_id": {
            "type": "string",
            "nullable": true,
            "example": "34288f14-7d3e-4275-8b14-3df6d116b1af"
          },
          "lead_id": {
            "type": "string",
            "nullable": true,
            "example": "c1b1c601-6707-4d3a-8c1a-ec0127358019"
          },
          "opportunity_id": {
            "type": "string",
            "nullable": true,
            "example": "2506e5f3-1805-405a-a13c-baa0ac524274"
          },
          "custom_fields": {
            "$ref": "#/components/schemas/custom_fields"
          }
        }
      },
      "lead": {
        "type": "object",
        "properties": {
          "addresses": {
            "$ref": "#/components/schemas/addresses"
          },
          "company": {
            "type": "string",
            "nullable": true,
            "example": "Supaglue"
          },
          "converted_account_id": {
            "type": "string",
            "nullable": true,
            "example": "88cc44ca-7a34-4e8b-b0da-51c3aae34daf"
          },
          "converted_account": {
            "$ref": "#/components/schemas/account"
          },
          "converted_contact_id": {
            "type": "string",
            "nullable": true,
            "example": "8c8de778-a219-4d6c-848c-1d57b52149f6"
          },
          "converted_contact": {
            "$ref": "#/components/schemas/contact"
          },
          "converted_date": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2023-02-27T00:00:00Z"
          },
          "email_addresses": {
            "$ref": "#/components/schemas/email_addresses"
          },
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "id": {
            "type": "string",
            "example": 54312
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "lead_source": {
            "type": "string",
            "nullable": true,
            "example": "API Blogger"
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "62e5e0f7-becd-4ae2-be82-8b4e1d5ed8a2"
          },
          "owner": {
            "$ref": "#/components/schemas/user"
          },
          "phone_numbers": {
            "$ref": "#/components/schemas/phone_numbers"
          },
          "title": {
            "type": "string",
            "nullable": true,
            "example": "Co-Founder"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2023-02-10T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2023-02-10T00:00:00Z"
          },
          "was_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "addresses",
          "company",
          "converted_account_id",
          "converted_contact_id",
          "converted_date",
          "id",
          "last_name",
          "lead_source",
          "owner_id",
          "phone_numbers",
          "title",
          "created_at",
          "updated_at",
          "was_deleted",
          "last_modified_at"
        ]
      },
      "create_update_lead": {
        "type": "object",
        "properties": {
          "company": {
            "type": "string",
            "nullable": true,
            "example": "Supaglue"
          },
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "lead_source": {
            "type": "string",
            "nullable": true,
            "example": "API Blogger"
          },
          "title": {
            "type": "string",
            "example": "Co-Founder"
          },
          "email_addresses": {
            "$ref": "#/components/schemas/email_addresses"
          },
          "addresses": {
            "$ref": "#/components/schemas/addresses"
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "9f3e97fd-4d5d-4efc-959d-bbebfac079f5"
          },
          "custom_fields": {
            "$ref": "#/components/schemas/custom_fields"
          }
        }
      },
      "opportunity": {
        "type": "object",
        "properties": {
          "account_id": {
            "type": "string",
            "nullable": true,
            "example": "fd089246-09b1-4e3b-a60a-7a76314bbcce"
          },
          "account": {
            "$ref": "#/components/schemas/account"
          },
          "amount": {
            "type": "integer",
            "nullable": true,
            "example": 100000
          },
          "close_date": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2023-02-27T00:00:00Z"
          },
          "description": {
            "type": "string",
            "nullable": true,
            "example": "Wants to use open source unified API for third-party integrations"
          },
          "id": {
            "type": "string",
            "example": 54312
          },
          "last_activity_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2023-02-27T00:00:00Z"
          },
          "name": {
            "type": "string",
            "nullable": true,
            "example": "Needs third-party integrations"
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          },
          "owner": {
            "$ref": "#/components/schemas/user"
          },
          "pipeline": {
            "type": "string",
            "nullable": true
          },
          "stage": {
            "type": "string",
            "nullable": true,
            "example": "Closed Won"
          },
          "status": {
            "type": "string",
            "nullable": true,
            "example": "OPEN"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2023-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2023-02-27T00:00:00Z"
          },
          "was_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "account_id",
          "amount",
          "description",
          "id",
          "last_activity_at",
          "name",
          "owner_id",
          "stage",
          "status",
          "pipeline",
          "created_at",
          "updated_at",
          "was_deleted",
          "last_modified_at"
        ]
      },
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": 54312
          },
          "name": {
            "type": "string",
            "nullable": true,
            "example": "George Xing"
          },
          "email": {
            "type": "string",
            "nullable": true,
            "example": "george@supaglue.com"
          },
          "is_active": {
            "type": "boolean",
            "nullable": true
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "was_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "name",
          "email",
          "is_active",
          "created_at",
          "updated_at",
          "was_deleted",
          "last_modified_at"
        ]
      },
      "create_update_opportunity": {
        "type": "object",
        "properties": {
          "amount": {
            "type": "integer",
            "nullable": true,
            "example": 100000
          },
          "close_date": {
            "type": "string",
            "nullable": true,
            "example": "2022-02-10T00:00:00Z"
          },
          "description": {
            "type": "string",
            "nullable": true,
            "example": "Wants to use open source unified API for third-party integrations"
          },
          "name": {
            "type": "string",
            "nullable": true,
            "example": "Needs Integrations"
          },
          "stage": {
            "type": "string",
            "example": "Closed Won"
          },
          "account_id": {
            "type": "string",
            "nullable": true,
            "example": "64571bff-48ea-4469-9fa0-ee1a0bab38bd"
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "9f3e97fd-4d5d-4efc-959d-bbebfac079f5"
          },
          "pipeline": {
            "type": "string",
            "nullable": true
          },
          "custom_fields": {
            "$ref": "#/components/schemas/custom_fields"
          }
        }
      },
      "logs": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "dashboard_view": {
              "type": "string",
              "example": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832"
            },
            "log_id": {
              "type": "string",
              "example": "99433219-8017-4acd-bb3c-ceb23d663832"
            },
            "log_summary": {
              "type": "object",
              "properties": {
                "method": {
                  "type": "string",
                  "example": "POST"
                },
                "status_code": {
                  "type": "number",
                  "example": 200
                },
                "url": {
                  "type": "string",
                  "example": "https://harvest.greenhouse.io/v1/candidates/"
                }
              }
            }
          }
        },
        "example": [
          {
            "dashboard_view": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832",
            "log_id": "99433219-8017-4acd-bb3c-ceb23d663832",
            "log_summary": {
              "method": "POST",
              "status_code": 200,
              "url": "https://harvest.greenhouse.io/v1/candidates/"
            }
          },
          {
            "dashboard_view": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832",
            "log_id": "99433219-8017-4acd-bb3c-ceb23d663832",
            "log_summary": {
              "method": "POST",
              "status_code": 200,
              "url": "https://harvest.greenhouse.io/v1/candidates/"
            }
          }
        ]
      },
      "errors": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "detail": {
              "type": "string",
              "example": "name is a required field on model."
            },
            "problem_type": {
              "type": "string",
              "example": "MISSING_REQUIRED_FIELD"
            },
            "source": {
              "type": "object",
              "properties": {
                "pointer": {
                  "type": "string",
                  "example": "irure consectetur"
                }
              }
            },
            "title": {
              "type": "string",
              "example": "Missing Required Field"
            }
          },
          "example": [
            {
              "detail": "name is a required field on model.",
              "problem_type": "MISSING_REQUIRED_FIELD",
              "source": {
                "pointer": "irure consectetur"
              },
              "title": "Missing Required Field"
            },
            {
              "detail": "name is a required field on model.",
              "problem_type": "MISSING_REQUIRED_FIELD",
              "source": {
                "pointer": "et"
              },
              "title": "Missing Required Field"
            }
          ]
        }
      },
      "warnings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "detail": {
              "type": "string",
              "example": "An unrecognized field, age, was passed in with request data."
            },
            "problem_type": {
              "type": "string",
              "example": "UNRECOGNIZED_FIELD"
            },
            "source": {
              "type": "object",
              "properties": {
                "pointer": {
                  "type": "string",
                  "example": "Lorem ipsum"
                }
              }
            },
            "title": {
              "type": "string",
              "example": "Unrecognized Field"
            }
          }
        },
        "example": [
          {
            "detail": "An unrecognized field, age, was passed in with request data.",
            "problem_type": "UNRECOGNIZED_FIELD",
            "source": {
              "pointer": "Lorem ipsum"
            },
            "title": "Unrecognized Field"
          },
          {
            "detail": "An unrecognized field, age, was passed in with request data.",
            "problem_type": "UNRECOGNIZED_FIELD",
            "source": {
              "pointer": "in"
            },
            "title": "Unrecognized Field"
          }
        ]
      },
      "addresses": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "address_type": {
              "type": "string",
              "enum": [
                "primary",
                "mailing",
                "other",
                "billing",
                "shipping"
              ]
            },
            "city": {
              "type": "string",
              "nullable": true,
              "example": "San Francisco"
            },
            "country": {
              "type": "string",
              "nullable": true,
              "example": "USA"
            },
            "postal_code": {
              "type": "string",
              "nullable": true,
              "example": "94107"
            },
            "state": {
              "type": "string",
              "nullable": true,
              "example": "CA"
            },
            "street_1": {
              "type": "string",
              "nullable": true,
              "example": "525 Brannan"
            },
            "street_2": {
              "type": "string",
              "nullable": true,
              "example": null
            }
          },
          "required": [
            "address_type",
            "city",
            "country",
            "postal_code",
            "state",
            "street_1",
            "street_2"
          ]
        },
        "example": [
          {
            "address_type": "shipping",
            "city": "San Francisco",
            "country": "US",
            "postal_code": "94107",
            "state": "CA",
            "street_1": "525 Brannan",
            "street_2": null
          }
        ]
      },
      "email_addresses": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "email_address": {
              "type": "string",
              "example": "hello@supaglue.com"
            },
            "email_address_type": {
              "type": "string",
              "enum": [
                "primary",
                "work"
              ]
            }
          },
          "required": [
            "email_address",
            "email_address_type"
          ]
        },
        "example": [
          {
            "email_address": "hello@supaglue.com",
            "email_address_type": "work"
          }
        ]
      },
      "phone_numbers": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "phone_number": {
              "type": "string",
              "nullable": true,
              "example": "+14151234567"
            },
            "phone_number_type": {
              "type": "string",
              "enum": [
                "primary",
                "mobile",
                "fax"
              ]
            }
          },
          "required": [
            "phone_number",
            "phone_number_type"
          ]
        },
        "example": [
          {
            "phone_number": "+14151234567",
            "phone_number_type": "primary"
          }
        ]
      },
      "pagination": {
        "type": "object",
        "properties": {
          "next": {
            "type": "string",
            "nullable": true,
            "example": "eyJpZCI6IjQyNTc5ZjczLTg1MjQtNDU3MC05YjY3LWVjYmQ3MDJjNmIxNCIsInJldmVyc2UiOmZhbHNlfQ=="
          },
          "previous": {
            "type": "string",
            "nullable": true,
            "example": "eyJpZCI6IjBjZDhmYmZkLWU5NmQtNDEwZC05ZjQxLWIwMjU1YjdmNGI4NyIsInJldmVyc2UiOnRydWV9"
          }
        }
      },
      "custom_fields": {
        "type": "object",
        "additionalProperties": true,
        "description": "Custom properties to be inserted that are not covered by the common model. Object keys must match exactly to the corresponding provider API."
      },
      "filter": {
        "oneOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "type": {
                "type": "string",
                "enum": [
                  "equals"
                ]
              },
              "value": {
                "type": "string"
              }
            },
            "required": [
              "type",
              "value"
            ]
          }
        ]
      },
      "lifecycle_stage": {
        "type": "string",
        "nullable": true,
        "enum": [
          "subscriber",
          "lead",
          "marketingqualifiedlead",
          "salesqualifiedlead",
          "opportunity",
          "customer",
          "evangelist",
          "other"
        ]
      }
    },
    "parameters": {
      "x-customer-id": {
        "name": "x-customer-id",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "my-customer-1"
        },
        "description": "The customer ID that uniquely identifies the customer in your application",
        "required": true
      },
      "x-provider-name": {
        "name": "x-provider-name",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "salesforce"
        },
        "description": "The provider name",
        "required": true
      }
    }
  }
}