{
  "openapi": "3.0.3",
  "info": {
    "version": "0.3.3",
    "title": "Supaglue Management API",
    "contact": {
      "name": "Supaglue",
      "email": "docs@supaglue.com",
      "url": "https://supaglue.com"
    },
    "description": "# Introduction\n\nWelcome to the Supaglue Management API documentation. You can use this API to manage customer integrations and connections.\n\n### Base API URL\n\n```\nhttp://localhost:8080/mgmt/v1\n```\n"
  },
  "externalDocs": {
    "description": "Try out our API in Postman!",
    "url": "https://www.postman.com/supaglue/workspace/supaglue-public/overview"
  },
  "servers": [
    {
      "url": "http://localhost:8080/mgmt/v1",
      "description": "Local Supaglue API"
    }
  ],
  "paths": {
    "/customers": {
      "get": {
        "operationId": "getCustomers",
        "tags": [
          "Customers"
        ],
        "summary": "List customers",
        "description": "Get a list of customers",
        "responses": {
          "200": {
            "description": "Customers",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/customer"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "id": "7393b5a4-5e20-4648-87af-b7b297793fd1",
                        "application_id": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
                      },
                      {
                        "id": "e888cedf-e9d0-42c5-9485-2d72984faef2",
                        "application_id": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "createCustomer",
        "summary": "Create customer",
        "tags": [
          "Customers"
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/create_update_customer"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Customer created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/customer"
                }
              }
            }
          }
        }
      }
    },
    "/customers/{customer_id}": {
      "get": {
        "operationId": "getCustomer",
        "summary": "Get customer",
        "tags": [
          "Customers"
        ],
        "responses": {
          "200": {
            "description": "Customer",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/customer"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": "0258cbc6-6020-430a-848e-aafacbadf4ae",
                      "application_id": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "deleteCustomer",
        "summary": "Delete customer",
        "tags": [
          "Customers"
        ],
        "responses": {
          "200": {
            "description": "Customer",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/customer"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": "0258cbc6-6020-430a-848e-aafacbadf4ae",
                      "application_id": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "name": "customer_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/integrations": {
      "get": {
        "operationId": "getIntegrations",
        "tags": [
          "Integrations"
        ],
        "summary": "List integrations",
        "description": "Get a list of integrations",
        "responses": {
          "200": {
            "description": "Integrations",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/integration"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "id": "e888cedf-e9d0-42c5-9485-2d72984faef2",
                        "category": "crm",
                        "auth_type": "oauth2",
                        "provider_name": "hubspot",
                        "config": [
                          {
                            "remote_provider_app_id": "my_app_id",
                            "oauth": [
                              {
                                "oauth_scopes": [
                                  "crm.objects.contacts.read",
                                  "crm.objects.companies.read",
                                  "crm.objects.deals.read",
                                  "crm.objects.contacts.write",
                                  "crm.objects.companies.write",
                                  "crm.objects.deals.write"
                                ],
                                "credentials": [
                                  {
                                    "oauth_client_id": "7393b5a4-5e20-4648-87af-b7b297793fd1",
                                    "oauth_client_secret": "941b846a-5a8c-48b8-b0e1-41b6d4bc4f1a"
                                  }
                                ]
                              }
                            ]
                          },
                          {
                            "sync": [
                              {
                                "period_ms": 60000
                              }
                            ]
                          }
                        ]
                      },
                      {
                        "id": "cb40ff24-6587-4b24-82a3-9269a05d5dda",
                        "category": "crm",
                        "auth_type": "oauth2",
                        "provider_name": "salesforce",
                        "config": [
                          {
                            "remote_provider_app_id": "my_app_id2",
                            "oauth": [
                              {
                                "oauth_scopes": [
                                  "crm.objects.contacts.read",
                                  "crm.objects.companies.read",
                                  "crm.objects.deals.read",
                                  "crm.objects.contacts.write",
                                  "crm.objects.companies.write",
                                  "crm.objects.deals.write"
                                ],
                                "credentials": [
                                  {
                                    "oauth_client_id": "7393b5a4-5e20-4648-87af-b7b297793fd1",
                                    "oauth_client_secret": "941b846a-5a8c-48b8-b0e1-41b6d4bc4f1a"
                                  }
                                ]
                              }
                            ]
                          },
                          {
                            "sync": [
                              {
                                "period_ms": 60000
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "createIntegration",
        "summary": "Create integration",
        "tags": [
          "Integrations"
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/create_update_integration"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Integration created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/integration"
                }
              }
            }
          }
        }
      }
    },
    "/integrations/{integration_id}": {
      "get": {
        "operationId": "getIntegration",
        "summary": "Get integration",
        "tags": [
          "Integrations"
        ],
        "responses": {
          "200": {
            "description": "Integration",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/integration"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": "e888cedf-e9d0-42c5-9485-2d72984faef2",
                      "category": "crm",
                      "auth_type": "oauth2",
                      "provider_name": "hubspot",
                      "config": [
                        {
                          "remote_provider_app_id": "my_app_id",
                          "oauth": [
                            {
                              "oauth_scopes": [
                                "crm.objects.contacts.read",
                                "crm.objects.companies.read",
                                "crm.objects.deals.read",
                                "crm.objects.contacts.write",
                                "crm.objects.companies.write",
                                "crm.objects.deals.write"
                              ],
                              "credentials": [
                                {
                                  "oauth_client_id": "7393b5a4-5e20-4648-87af-b7b297793fd1",
                                  "oauth_client_secret": "941b846a-5a8c-48b8-b0e1-41b6d4bc4f1a"
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "sync": [
                            {
                              "period_ms": 60000
                            }
                          ]
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "operationId": "updateIntegration",
        "summary": "Update integration",
        "tags": [
          "Integrations"
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/create_update_integration"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Integration",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/integration"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": "e888cedf-e9d0-42c5-9485-2d72984faef2",
                      "category": "crm",
                      "auth_type": "oauth2",
                      "provider_name": "hubspot",
                      "config": [
                        {
                          "remote_provider_app_id": "my_app_id",
                          "oauth": [
                            {
                              "oauth_scopes": [
                                "crm.objects.contacts.read",
                                "crm.objects.companies.read",
                                "crm.objects.deals.read",
                                "crm.objects.contacts.write",
                                "crm.objects.companies.write",
                                "crm.objects.deals.write"
                              ],
                              "credentials": [
                                {
                                  "oauth_client_id": "7393b5a4-5e20-4648-87af-b7b297793fd1",
                                  "oauth_client_secret": "941b846a-5a8c-48b8-b0e1-41b6d4bc4f1a"
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "sync": [
                            {
                              "period_ms": 60000
                            }
                          ]
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "deleteIntegration",
        "summary": "Delete integration",
        "tags": [
          "Integrations"
        ],
        "responses": {
          "200": {
            "description": "Integration",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/integration"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": "e888cedf-e9d0-42c5-9485-2d72984faef2",
                      "category": "crm",
                      "auth_type": "oauth2",
                      "provider_name": "hubspot",
                      "config": [
                        {
                          "remote_provider_app_id": "my_app_id",
                          "oauth": [
                            {
                              "oauth_scopes": [
                                "crm.objects.contacts.read",
                                "crm.objects.companies.read",
                                "crm.objects.deals.read",
                                "crm.objects.contacts.write",
                                "crm.objects.companies.write",
                                "crm.objects.deals.write"
                              ],
                              "credentials": [
                                {
                                  "oauth_client_id": "7393b5a4-5e20-4648-87af-b7b297793fd1",
                                  "oauth_client_secret": "941b846a-5a8c-48b8-b0e1-41b6d4bc4f1a"
                                }
                              ]
                            }
                          ]
                        },
                        {
                          "sync": [
                            {
                              "period_ms": 60000
                            }
                          ]
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "name": "integration_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/customers/{customer_id}/connections": {
      "get": {
        "operationId": "getConnections",
        "tags": [
          "Connections"
        ],
        "summary": "List connections",
        "description": "Get a list of connections",
        "responses": {
          "200": {
            "description": "Connections",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/connection"
                  }
                },
                "examples": {
                  "Example": {
                    "value": [
                      {
                        "id": "9572d08b-f19f-48cc-a992-1eb7031d3f6a",
                        "customer_id": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69",
                        "status": "available",
                        "integration_id": "9572d08b-f19f-48cc-a992-1eb7031d3f6a",
                        "provider_name": "salesforce",
                        "category": "crm",
                        "credentials": [
                          {
                            "type": "oauth2",
                            "access_token": "00DDn000004L1rN!AQwAQFcdcvZCaMN83FUDEI5BHyjWILUCMH91UOX7xPVAgn2DjT9LrYTX8RT9vSQ281kBUtQBNsjBKC6R4lIlQTLLvCTuYxtJ",
                            "refresh_token": "5Aep861J.7rrvmXwLwV8Hw86X7cQtxqOq1cNOt9LLourdPAeVgOQHl7idtvQp_e70Q_r20DpwpB4Mo.45QlO29e",
                            "instance_url": "https://myapp-dev-ed.develop.my.salesforce.com",
                            "expires_at": "2023-03-09T21:55:54.000Z"
                          }
                        ]
                      },
                      {
                        "id": "e888cedf-e9d0-42c5-9485-2d72984faef2",
                        "customer_id": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69",
                        "status": "available",
                        "integration_id": "9572d08b-f19f-48cc-a992-1eb7031d3f6a",
                        "provider_name": "salesforce",
                        "category": "crm",
                        "credentials": [
                          {
                            "type": "oauth2",
                            "access_token": "00DDn000004L1rN!AQwAQFcdcvZCaMN83FUDEI5BHyjWILUCMH91UOX7xPVAgn2DjT9LrYTX8RT9vSQ281kBUtQBNsjBKC6R4lIlQTLLvCTuYxtJ",
                            "refresh_token": "5Aep861J.7rrvmXwLwV8Hw86X7cQtxqOq1cNOt9LLourdPAeVgOQHl7idtvQp_e70Q_r20DpwpB4Mo.45QlO29e",
                            "instance_url": "https://myapp2-dev-ed.develop.my.salesforce.com",
                            "expires_at": "2023-03-09T21:55:54.000Z"
                          }
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "name": "customer_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/customers/{customer_id}/connections/{connection_id}": {
      "get": {
        "operationId": "getConnection",
        "summary": "Get connection",
        "tags": [
          "Connections"
        ],
        "responses": {
          "200": {
            "description": "Connection",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/connection"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": "9572d08b-f19f-48cc-a992-1eb7031d3f6a",
                      "customer_id": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69",
                      "status": "available",
                      "integration_id": "9572d08b-f19f-48cc-a992-1eb7031d3f6a",
                      "provider_name": "salesforce",
                      "category": "crm",
                      "credentials": [
                        {
                          "type": "oauth2",
                          "access_token": "00DDn000004L1rN!AQwAQFcdcvZCaMN83FUDEI5BHyjWILUCMH91UOX7xPVAgn2DjT9LrYTX8RT9vSQ281kBUtQBNsjBKC6R4lIlQTLLvCTuYxtJ",
                          "refresh_token": "5Aep861J.7rrvmXwLwV8Hw86X7cQtxqOq1cNOt9LLourdPAeVgOQHl7idtvQp_e70Q_r20DpwpB4Mo.45QlO29e",
                          "instance_url": "https://myapp-dev-ed.develop.my.salesforce.com",
                          "expires_at": "2023-03-09T21:55:54.000Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "operationId": "deleteConnection",
        "summary": "Delete connection",
        "tags": [
          "Connections"
        ],
        "responses": {
          "200": {
            "description": "Connection",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/connection"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": "9572d08b-f19f-48cc-a992-1eb7031d3f6a",
                      "customer_id": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69",
                      "status": "available",
                      "integration_id": "9572d08b-f19f-48cc-a992-1eb7031d3f6a",
                      "provider_name": "salesforce",
                      "category": "crm",
                      "credentials": [
                        {
                          "type": "oauth2",
                          "access_token": "00DDn000004L1rN!AQwAQFcdcvZCaMN83FUDEI5BHyjWILUCMH91UOX7xPVAgn2DjT9LrYTX8RT9vSQ281kBUtQBNsjBKC6R4lIlQTLLvCTuYxtJ",
                          "refresh_token": "5Aep861J.7rrvmXwLwV8Hw86X7cQtxqOq1cNOt9LLourdPAeVgOQHl7idtvQp_e70Q_r20DpwpB4Mo.45QlO29e",
                          "instance_url": "https://myapp-dev-ed.develop.my.salesforce.com",
                          "expires_at": "2023-03-09T21:55:54.000Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "name": "customer_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        },
        {
          "name": "connection_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    }
  },
  "tags": [],
  "components": {
    "schemas": {
      "customer": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "e888cedf-e9d0-42c5-9485-2d72984faef2"
          },
          "application_id": {
            "type": "string",
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          },
          "connections": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/connection"
            }
          }
        },
        "required": [
          "id",
          "application_id"
        ],
        "example": [
          {
            "id": "e888cedf-e9d0-42c5-9485-2d72984faef2"
          },
          {
            "application_id": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          }
        ]
      },
      "integration": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "e888cedf-e9d0-42c5-9485-2d72984faef2"
          },
          "application_id": {
            "type": "string",
            "example": "9572d08b-f19f-48cc-a992-1eb7031d3f6a"
          },
          "category": {
            "$ref": "#/components/schemas/category"
          },
          "auth_type": {
            "type": "string",
            "enum": [
              "oauth2"
            ]
          },
          "provider_name": {
            "$ref": "#/components/schemas/provider_name"
          },
          "config": {
            "$ref": "#/components/schemas/integration_config"
          }
        },
        "required": [
          "id",
          "application_id",
          "category",
          "auth_type",
          "provider_name",
          "config"
        ],
        "example": [
          {
            "id": "e888cedf-e9d0-42c5-9485-2d72984faef2",
            "category": "crm",
            "auth_type": "oauth2",
            "provider_name": "hubspot",
            "config": [
              {
                "remote_provider_app_id": "my_app_id",
                "oauth": [
                  {
                    "oauth_scopes": [
                      "crm.objects.contacts.read",
                      "crm.objects.companies.read",
                      "crm.objects.deals.read",
                      "crm.objects.contacts.write",
                      "crm.objects.companies.write",
                      "crm.objects.deals.write"
                    ],
                    "credentials": [
                      {
                        "oauth_client_id": "7393b5a4-5e20-4648-87af-b7b297793fd1",
                        "oauth_client_secret": "941b846a-5a8c-48b8-b0e1-41b6d4bc4f1a"
                      }
                    ]
                  }
                ]
              },
              {
                "sync": [
                  {
                    "period_ms": 60000
                  }
                ]
              }
            ]
          }
        ]
      },
      "connection": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "e888cedf-e9d0-42c5-9485-2d72984faef2"
          },
          "status": {
            "type": "string",
            "enum": [
              "available",
              "added",
              "authorized",
              "callable"
            ],
            "example": "available"
          },
          "customer_id": {
            "type": "string",
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          },
          "integration_id": {
            "type": "string",
            "example": "9572d08b-f19f-48cc-a992-1eb7031d3f6a"
          },
          "credentials": {
            "$ref": "#/components/schemas/connection_credentials"
          },
          "provider_name": {
            "$ref": "#/components/schemas/provider_name"
          },
          "category": {
            "$ref": "#/components/schemas/category"
          }
        },
        "required": [
          "id",
          "status",
          "customer_id",
          "integration_id",
          "credentials",
          "provider_name",
          "category"
        ],
        "example": [
          {
            "id": "e888cedf-e9d0-42c5-9485-2d72984faef2",
            "customer_id": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69",
            "status": "available",
            "integration_id": "9572d08b-f19f-48cc-a992-1eb7031d3f6a",
            "provider_name": "salesforce",
            "category": "crm",
            "credentials": [
              {
                "type": "oauth2",
                "access_token": "00DDn000004L1rN!AQwAQFcdcvZCaMN83FUDEI5BHyjWILUCMH91UOX7xPVAgn2DjT9LrYTX8RT9vSQ281kBUtQBNsjBKC6R4lIlQTLLvCTuYxtJ",
                "refresh_token": "5Aep861J.7rrvmXwLwV8Hw86X7cQtxqOq1cNOt9LLourdPAeVgOQHl7idtvQp_e70Q_r20DpwpB4Mo.45QlO29e",
                "instance_url": "https://myapp-dev-ed.develop.my.salesforce.com",
                "expires_at": "2023-03-09T21:55:54.000Z"
              }
            ]
          }
        ]
      },
      "connection_credentials": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "example": "oauth2"
          },
          "access_token": {
            "type": "string",
            "example": "00DDn000004L1rN!AQwAQFcdcvZCaMN83FUDEI5BHyjWILUCMH91UOX7xPVAgn2DjT9LrYTX8RT9vSQ281kBUtQBNsjBKC6R4lIlQTLLvCTuYxtJ"
          },
          "refresh_token": {
            "type": "string",
            "example": "5Aep861J.7rrvmXwLwV8Hw86X7cQtxqOq1cNOt9LLourdPAeVgOQHl7idtvQp_e70Q_r20DpwpB4Mo.45QlO29e"
          },
          "instance_url": {
            "type": "string",
            "example": "https://myapp-dev-ed.develop.my.salesforce.com"
          },
          "expires_at": {
            "type": "string",
            "nullable": true,
            "example": "2023-03-09T21:55:54.000Z"
          }
        },
        "example": [
          {
            "type": "oauth2",
            "access_token": "00DDn000004L1rN!AQwAQFcdcvZCaMN83FUDEI5BHyjWILUCMH91UOX7xPVAgn2DjT9LrYTX8RT9vSQ281kBUtQBNsjBKC6R4lIlQTLLvCTuYxtJ",
            "refresh_token": "5Aep861J.7rrvmXwLwV8Hw86X7cQtxqOq1cNOt9LLourdPAeVgOQHl7idtvQp_e70Q_r20DpwpB4Mo.45QlO29e",
            "instance_url": "https://myapp-dev-ed.develop.my.salesforce.com",
            "expires_at": "2023-03-09T21:55:54.000Z"
          }
        ]
      },
      "category": {
        "type": "string",
        "enum": [
          "crm"
        ]
      },
      "integration_config": {
        "type": "object",
        "properties": {
          "remote_provider_app_id": {
            "type": "string",
            "example": "my_app_id"
          },
          "oauth": {
            "type": "object",
            "properties": {
              "oauth_scopes": {
                "type": "array",
                "items": {
                  "type": "string",
                  "example": "crm.objects.contacts.read"
                }
              },
              "credentials": {
                "type": "object",
                "properties": {
                  "oauth_client_id": {
                    "type": "string",
                    "example": "7393b5a4-5e20-4648-87af-b7b297793fd1"
                  },
                  "oauth_client_secret": {
                    "type": "string",
                    "example": "941b846a-5a8c-48b8-b0e1-41b6d4bc4f1a"
                  }
                },
                "required": [
                  "oauth_client_id",
                  "oauth_client_secret"
                ]
              }
            },
            "required": [
              "oauth_scopes",
              "credentials"
            ]
          },
          "sync": {
            "type": "object",
            "properties": {
              "period_ms": {
                "type": "integer",
                "example": 60000
              }
            },
            "required": [
              "period_ms"
            ]
          }
        },
        "required": [
          "remote_provider_app_id",
          "oauth",
          "sync"
        ],
        "example": [
          {
            "remote_provider_app_id": "my_app_id"
          },
          {
            "oauth": [
              {
                "oauth_scopes": [
                  "crm.objects.contacts.read",
                  "crm.objects.companies.read",
                  "crm.objects.deals.read",
                  "crm.objects.contacts.write",
                  "crm.objects.companies.write",
                  "crm.objects.deals.write"
                ]
              },
              {
                "credentials": [
                  {
                    "oauth_client_id": "7393b5a4-5e20-4648-87af-b7b297793fd1"
                  },
                  {
                    "oauth_client_secret": "941b846a-5a8c-48b8-b0e1-41b6d4bc4f1a"
                  }
                ]
              }
            ]
          },
          {
            "sync": [
              {
                "period_ms": 60000
              }
            ]
          }
        ]
      },
      "provider_name": {
        "type": "string",
        "enum": [
          "hubspot",
          "salesforce",
          "pipedrive",
          "zendesk_sell",
          "ms_dynamics_365_sales",
          "zoho_crm",
          "capsule"
        ]
      },
      "create_update_customer": {
        "type": "object",
        "properties": {
          "application_id": {
            "type": "string",
            "example": "d8ceb3ff-8b7f-4fa7-b8de-849292f6ca69"
          }
        },
        "required": [
          "application_id"
        ]
      },
      "create_update_integration": {
        "type": "object",
        "properties": {
          "application_id": {
            "type": "string",
            "example": "9572d08b-f19f-48cc-a992-1eb7031d3f6a"
          },
          "category": {
            "$ref": "#/components/schemas/category"
          },
          "auth_type": {
            "type": "string",
            "enum": [
              "oauth2"
            ]
          },
          "provider_name": {
            "$ref": "#/components/schemas/provider_name"
          },
          "config": {
            "$ref": "#/components/schemas/integration_config"
          }
        },
        "required": [
          "application_id",
          "category",
          "auth_type",
          "provider_name",
          "config"
        ]
      }
    }
  }
}