{
  "openapi": "3.0.3",
  "info": {
    "version": "0.12.12",
    "title": "Supaglue Object Actions API",
    "contact": {
      "name": "Supaglue"
    },
    "description": "#### Introduction\n\nWelcome to the Supaglue Object Actions API documentation. You can use this API to perform CRUD on Object records in third-party providers.\n\n[![Run in Postman](https://run.pstmn.io/button.svg)](https://www.postman.com/supaglue/workspace/supaglue-public/overview)\n\n#### Base API URL\n```\nhttps://api.supaglue.io/object_actions/standard/v2\n```\n"
  },
  "servers": [
    {
      "url": "https://api.supaglue.io/object_actions/v2",
      "description": "Supaglue API"
    }
  ],
  "paths": {
    "/standard/{object_name}": {
      "post": {
        "operationId": "create",
        "summary": "Create Standard Object record",
        "tags": [
          "ObjectRecords"
        ],
        "security": [
          {
            "x-api-key": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "$ref": "#/components/schemas/create_update_standard_object_record"
                  }
                },
                "required": [
                  "data"
                ],
                "example": {
                  "data": {
                    "Name": "Acme Corp",
                    "Description": "We create the best embedded integration platforms."
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Standard ObjectRecord created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "record": {
                      "$ref": "#/components/schemas/created_standard_object_record"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "object_name",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "Account"
          }
        }
      ]
    },
    "/standard/{object_name}/{record_id}": {
      "get": {
        "operationId": "getStandardObjectRecord",
        "summary": "Get Standard Object record",
        "tags": [
          "ObjectRecords"
        ],
        "security": [
          {
            "x-api-key": []
          }
        ],
        "responses": {
          "200": {
            "description": "Standard object record",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/standard_object_record"
                },
                "examples": {
                  "Example": {
                    "value": {
                      "id": "001Fn00023f8oYYIA0",
                      "standard_object_name": "Account",
                      "data": {
                        "Name": "Acme Corp",
                        "Description": "We create the best embedded integration platforms."
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "operationId": "updateStandardObjectRecord",
        "summary": "Update Standard Object record",
        "tags": [
          "ObjectRecords"
        ],
        "security": [
          {
            "x-api-key": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "data": {
                    "$ref": "#/components/schemas/create_update_standard_object_record"
                  }
                },
                "required": [
                  "data"
                ],
                "example": {
                  "data": {
                    "Name": "Acme Corp",
                    "Description": "We create the best embedded integration platforms."
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Standard object record updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "object_name",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "Account"
          }
        },
        {
          "name": "record_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    }
  },
  "tags": [
    {
      "name": "ObjectRecords",
      "description": "An `Object Record` is a record of an `Object`."
    }
  ],
  "components": {
    "securitySchemes": {
      "x-api-key": {
        "type": "apiKey",
        "name": "x-api-key",
        "in": "header",
        "description": "API key to allow developers to access the API"
      }
    },
    "schemas": {
      "standard_object_record": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "standard_object_name": {
            "type": "string"
          },
          "data": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "required": [
          "id",
          "standard_object_name",
          "data"
        ]
      },
      "create_update_standard_object_record": {
        "type": "object",
        "additionalProperties": true
      },
      "created_standard_object_record": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "standard_object_name": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "standard_object_name"
        ]
      },
      "logs": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "dashboard_view": {
              "type": "string",
              "example": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832"
            },
            "log_id": {
              "type": "string",
              "example": "99433219-8017-4acd-bb3c-ceb23d663832"
            },
            "log_summary": {
              "type": "object",
              "properties": {
                "method": {
                  "type": "string",
                  "example": "POST"
                },
                "status_code": {
                  "type": "number",
                  "example": 200
                },
                "url": {
                  "type": "string",
                  "example": "https://harvest.greenhouse.io/v1/candidates/"
                }
              }
            }
          }
        },
        "example": [
          {
            "dashboard_view": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832",
            "log_id": "99433219-8017-4acd-bb3c-ceb23d663832",
            "log_summary": {
              "method": "POST",
              "status_code": 200,
              "url": "https://harvest.greenhouse.io/v1/candidates/"
            }
          },
          {
            "dashboard_view": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832",
            "log_id": "99433219-8017-4acd-bb3c-ceb23d663832",
            "log_summary": {
              "method": "POST",
              "status_code": 200,
              "url": "https://harvest.greenhouse.io/v1/candidates/"
            }
          }
        ]
      },
      "errors": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "detail": {
              "type": "string",
              "example": "name is a required field on model."
            },
            "problem_type": {
              "type": "string",
              "example": "MISSING_REQUIRED_FIELD"
            },
            "source": {
              "type": "object",
              "properties": {
                "pointer": {
                  "type": "string",
                  "example": "irure consectetur"
                }
              }
            },
            "title": {
              "type": "string",
              "example": "Missing Required Field"
            }
          },
          "example": [
            {
              "detail": "name is a required field on model.",
              "problem_type": "MISSING_REQUIRED_FIELD",
              "source": {
                "pointer": "irure consectetur"
              },
              "title": "Missing Required Field"
            },
            {
              "detail": "name is a required field on model.",
              "problem_type": "MISSING_REQUIRED_FIELD",
              "source": {
                "pointer": "et"
              },
              "title": "Missing Required Field"
            }
          ]
        }
      },
      "warnings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "detail": {
              "type": "string",
              "example": "An unrecognized field, age, was passed in with request data."
            },
            "problem_type": {
              "type": "string",
              "example": "UNRECOGNIZED_FIELD"
            },
            "source": {
              "type": "object",
              "properties": {
                "pointer": {
                  "type": "string",
                  "example": "Lorem ipsum"
                }
              }
            },
            "title": {
              "type": "string",
              "example": "Unrecognized Field"
            }
          }
        },
        "example": [
          {
            "detail": "An unrecognized field, age, was passed in with request data.",
            "problem_type": "UNRECOGNIZED_FIELD",
            "source": {
              "pointer": "Lorem ipsum"
            },
            "title": "Unrecognized Field"
          },
          {
            "detail": "An unrecognized field, age, was passed in with request data.",
            "problem_type": "UNRECOGNIZED_FIELD",
            "source": {
              "pointer": "in"
            },
            "title": "Unrecognized Field"
          }
        ]
      }
    },
    "parameters": {
      "x-customer-id": {
        "name": "x-customer-id",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "my-customer-1"
        },
        "description": "The customer ID that uniquely identifies the customer in your application",
        "required": true
      },
      "x-provider-name": {
        "name": "x-provider-name",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "salesforce"
        },
        "description": "The provider name",
        "required": true
      }
    }
  }
}