{
  "openapi": "3.0.3",
  "info": {
    "version": "0.7.6",
    "title": "Supaglue Engagement API",
    "contact": {
      "name": "Supaglue",
      "email": "docs@supaglue.com",
      "url": "https://supaglue.com"
    },
    "description": "# Introduction\n\nWelcome to the Supaglue unified Engagement API documentation. You can use this API to read data that has been synced into Supaglue from third-party providers.\n\n### Base API URL\n\n```\nhttp://localhost:8080/engagement/v1\n```\n"
  },
  "externalDocs": {
    "description": "Try out our API in Postman!",
    "url": "https://www.postman.com/supaglue/workspace/supaglue-public/overview"
  },
  "servers": [
    {
      "url": "http://localhost:8080/engagement/v1",
      "description": "Local Supaglue API"
    }
  ],
  "paths": {
    "/passthrough": {
      "post": {
        "operationId": "sendPassthroughRequest",
        "tags": [
          "Passthrough"
        ],
        "summary": "Send passthrough request",
        "description": "Send request directly to a provider",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "path": {
                    "type": "string",
                    "description": "The path to send the request to (do not pass the domain)"
                  },
                  "method": {
                    "type": "string",
                    "enum": [
                      "GET",
                      "POST",
                      "PUT",
                      "PATCH",
                      "DELETE"
                    ],
                    "example": "GET"
                  },
                  "headers": {
                    "type": "object",
                    "description": "Headers to pass to downstream",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "query": {
                    "type": "object",
                    "description": "Query parameters to pass to downstream",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "body": {
                    "type": "string",
                    "description": "Body to pass to downstream"
                  }
                },
                "required": [
                  "path",
                  "method"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Passthrough response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "url": {
                      "type": "string",
                      "description": "The full URL the request was went to",
                      "example": "https://customengagement.com/api/cars"
                    },
                    "status": {
                      "type": "number",
                      "description": "Status code from the downstream",
                      "example": 200
                    },
                    "headers": {
                      "type": "object",
                      "description": "The response headers from the downstream",
                      "additionalProperties": {
                        "type": "string"
                      }
                    },
                    "body": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "number"
                        },
                        {
                          "type": "integer"
                        },
                        {
                          "type": "boolean"
                        },
                        {
                          "type": "array",
                          "items": {
                            "additionalProperties": true
                          }
                        },
                        {
                          "type": "object",
                          "additionalProperties": true
                        }
                      ],
                      "description": "The body from the downstream"
                    }
                  },
                  "required": [
                    "url",
                    "status",
                    "headers"
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "url": "https://customengagement.com/api/cars",
                      "status": 200,
                      "headers": {
                        "x-requests-limit": 96
                      },
                      "body": []
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/contacts": {
      "post": {
        "operationId": "createContact",
        "summary": "Create contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_contact"
                  }
                },
                "required": [
                  "model"
                ]
              },
              "example": {
                "model": {
                  "first_name": "George",
                  "last_activity_at": "2022-02-10T00:00:00Z",
                  "last_name": "Xing",
                  "account_id": "64571bff-48ea-4469-9fa0-ee1a0bab38bd"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Contact created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "model": {
                      "$ref": "#/components/schemas/contact"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/sequences": {
      "post": {
        "operationId": "createSequence",
        "summary": "Create sequence",
        "tags": [
          "Sequences"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "model": {
                    "$ref": "#/components/schemas/create_sequence"
                  }
                },
                "required": [
                  "model"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sequence created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "model": {
                      "$ref": "#/components/schemas/sequence"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    }
  },
  "tags": [
    {
      "name": "Contacts",
      "description": "The `Contact` Common Model is used to represent a \"contact\" in Engagements."
    },
    {
      "name": "Sequences",
      "description": "The `Sequence` Common Model is used to represent a \"sequence\" in Engagements."
    },
    {
      "name": "Passthrough",
      "description": "Passthrough operations to underlying providers."
    }
  ],
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "name": "x-api-key",
        "in": "header",
        "description": "API key to allow developers to access the API"
      }
    },
    "schemas": {
      "contact": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": 54312
          },
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "job_title": {
            "type": "string",
            "nullable": true,
            "example": "CEO"
          },
          "address": {
            "$ref": "#/components/schemas/address"
          },
          "email_addresses": {
            "$ref": "#/components/schemas/email_addresses"
          },
          "phone_numbers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "phone_number": {
                  "type": "string",
                  "nullable": true,
                  "example": "+14151234567"
                },
                "phone_number_type": {
                  "type": "string",
                  "enum": [
                    "work",
                    "personal",
                    "other"
                  ]
                },
                "is_primary": {
                  "type": "boolean"
                }
              },
              "required": [
                "phone_number",
                "phone_number_type",
                "is_primary"
              ]
            },
            "example": [
              {
                "phone_number": "+14151234567",
                "phone_number_type": "work",
                "is_primary": true
              }
            ]
          },
          "open_count": {
            "type": "number"
          },
          "reply_count": {
            "type": "number"
          },
          "bounced_count": {
            "type": "number"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "first_name",
          "last_name",
          "job_title",
          "address",
          "email_addresses",
          "phone_numbers",
          "open_count",
          "click_count",
          "reply_count",
          "bounced_count",
          "created_at",
          "updated_at",
          "last_modified_at"
        ]
      },
      "create_contact": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "job_title": {
            "type": "string",
            "nullable": true,
            "example": "CEO"
          },
          "address": {
            "$ref": "#/components/schemas/address"
          },
          "email_addresses": {
            "$ref": "#/components/schemas/email_addresses"
          },
          "custom_fields": {
            "$ref": "#/components/schemas/custom_fields"
          }
        }
      },
      "sequence": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": 54312
          },
          "is_enabled": {
            "type": "boolean",
            "example": true
          },
          "name": {
            "type": "string"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "num_steps": {
            "type": "number"
          },
          "scheduled_count": {
            "type": "number"
          },
          "opted_out_count": {
            "type": "number"
          },
          "replied_count": {
            "type": "number"
          },
          "clicked_count": {
            "type": "number"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "is_enabled",
          "name",
          "tags",
          "num_steps",
          "scheduled_count",
          "opted_out_count",
          "replied_count",
          "clicked_count",
          "created_at",
          "updated_at",
          "last_modified_at"
        ]
      },
      "create_sequence": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "share_type": {
            "type": "string",
            "enum": [
              "team",
              "private"
            ]
          }
        },
        "required": [
          "name",
          "share_type"
        ]
      },
      "start_sequence": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "fields": {
            "type": "object",
            "properties": {
              "contact_id": {
                "type": "string"
              },
              "mailbox_id": {
                "type": "string"
              }
            },
            "required": [
              "contact_id",
              "mailbox_id"
            ]
          }
        },
        "required": [
          "id",
          "fields"
        ]
      },
      "pagination": {
        "type": "object",
        "properties": {
          "next": {
            "type": "string",
            "nullable": true,
            "example": "eyJpZCI6IjQyNTc5ZjczLTg1MjQtNDU3MC05YjY3LWVjYmQ3MDJjNmIxNCIsInJldmVyc2UiOmZhbHNlfQ=="
          },
          "previous": {
            "type": "string",
            "nullable": true,
            "example": "eyJpZCI6IjBjZDhmYmZkLWU5NmQtNDEwZC05ZjQxLWIwMjU1YjdmNGI4NyIsInJldmVyc2UiOnRydWV9"
          }
        }
      },
      "address": {
        "type": "object",
        "properties": {
          "city": {
            "type": "string",
            "nullable": true,
            "example": "San Francisco"
          },
          "country": {
            "type": "string",
            "nullable": true,
            "example": "USA"
          },
          "postal_code": {
            "type": "string",
            "nullable": true,
            "example": "94107"
          },
          "state": {
            "type": "string",
            "nullable": true,
            "example": "CA"
          },
          "street_1": {
            "type": "string",
            "nullable": true,
            "example": "525 Brannan"
          },
          "street_2": {
            "type": "string",
            "nullable": true,
            "example": null
          }
        },
        "required": [
          "city",
          "country",
          "postal_code",
          "state",
          "street_1",
          "street_2"
        ],
        "example": [
          {
            "city": "San Francisco",
            "country": "US",
            "postal_code": "94107",
            "state": "CA",
            "street_1": "525 Brannan",
            "street_2": null
          }
        ]
      },
      "email_addresses": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "email_address": {
              "type": "string",
              "example": "hello@supaglue.com"
            },
            "email_address_type": {
              "type": "string",
              "enum": [
                "personal",
                "work"
              ]
            },
            "is_primary": {
              "type": "boolean",
              "example": true
            }
          },
          "required": [
            "email_address",
            "email_address_type"
          ]
        },
        "example": [
          {
            "email_address": "hello@supaglue.com",
            "email_address_type": "work",
            "is_primary": true
          }
        ]
      },
      "custom_fields": {
        "type": "object",
        "additionalProperties": true,
        "description": "Custom properties to be inserted that are not covered by the common model. Object keys must match exactly to the corresponding provider API."
      }
    },
    "parameters": {
      "x-customer-id": {
        "name": "x-customer-id",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "my-customer-1"
        },
        "description": "The customer ID that uniquely identifies the customer in your application",
        "required": true
      },
      "x-provider-name": {
        "name": "x-provider-name",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "salesforce"
        },
        "description": "The provider name",
        "required": true
      }
    }
  }
}