{
  "openapi": "3.0.3",
  "info": {
    "version": "0.12.1",
    "title": "Supaglue Engagement API",
    "contact": {
      "name": "Supaglue"
    },
    "description": "#### Introduction\nWelcome to the Supaglue Actions API (Engagement) documentation. You can use this API to write to third-party providers.\n\n[![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/18172762-a211ef0f-e2e3-4ac0-b833-97125995c6f7?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D18172762-a211ef0f-e2e3-4ac0-b833-97125995c6f7%26entityType%3Dcollection%26workspaceId%3D4d2a33f3-a9f9-41f4-ac2e-5ad4db4a5edb)\n\n#### Reading data\nTo read data from third-party providers, refer to Supaglue's [Managed Syncs](https://docs.supaglue.com/integration-patterns/managed-syncs) feature.\n\n#### Base API URL\n\n```\nhttps://api.supaglue.io/engagement/v2\n```\n"
  },
  "servers": [
    {
      "url": "https://api.supaglue.io/engagement/v2",
      "description": "Supaglue API"
    }
  ],
  "paths": {
    "/passthrough": {
      "post": {
        "operationId": "sendPassthroughRequest",
        "tags": [
          "Passthrough"
        ],
        "summary": "Send passthrough request",
        "description": "Send request directly to a provider",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "path": {
                    "type": "string",
                    "description": "The path to send the request to (do not pass the domain)"
                  },
                  "method": {
                    "type": "string",
                    "enum": [
                      "GET",
                      "POST",
                      "PUT",
                      "PATCH",
                      "DELETE"
                    ],
                    "example": "GET"
                  },
                  "headers": {
                    "type": "object",
                    "description": "Headers to pass to downstream",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "query": {
                    "type": "object",
                    "description": "Query parameters to pass to downstream",
                    "additionalProperties": {
                      "type": "string"
                    }
                  },
                  "body": {
                    "type": "string",
                    "description": "Body to pass to downstream"
                  }
                },
                "required": [
                  "path",
                  "method"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Passthrough response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "url": {
                      "type": "string",
                      "description": "The full URL the request was went to",
                      "example": "https://customengagement.com/api/cars"
                    },
                    "status": {
                      "type": "number",
                      "description": "Status code from the downstream",
                      "example": 200
                    },
                    "headers": {
                      "type": "object",
                      "description": "The response headers from the downstream",
                      "additionalProperties": {
                        "type": "string"
                      }
                    },
                    "body": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "number"
                        },
                        {
                          "type": "integer"
                        },
                        {
                          "type": "boolean"
                        },
                        {
                          "type": "array",
                          "items": {
                            "additionalProperties": true
                          }
                        },
                        {
                          "type": "object",
                          "additionalProperties": true
                        }
                      ],
                      "description": "The body from the downstream"
                    }
                  },
                  "required": [
                    "url",
                    "status",
                    "headers"
                  ]
                },
                "examples": {
                  "Example": {
                    "value": {
                      "url": "https://customengagement.com/api/cars",
                      "status": 200,
                      "headers": {
                        "x-requests-limit": 96
                      },
                      "body": []
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/contacts": {
      "post": {
        "operationId": "createContact",
        "summary": "Create contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "record": {
                    "$ref": "#/components/schemas/create_contact"
                  }
                },
                "required": [
                  "record"
                ]
              },
              "example": {
                "record": {
                  "id": 1234,
                  "address": {
                    "city": "San Francisco",
                    "country": "USA",
                    "street_1": "525 Brannan St",
                    "street_2": null,
                    "postalCode": "94107",
                    "state": "CA"
                  },
                  "email_addresses": [
                    {
                      "email_address": "hello@supaglue.com",
                      "email_address_type": "workline2"
                    }
                  ],
                  "first_name": "George",
                  "last_name": "Xing",
                  "phone_numbers": [
                    {
                      "phone_number": "+14151234567",
                      "phone_number_type": "mobile"
                    }
                  ],
                  "created_at": "2023-02-27T00:00:00Z"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Contact created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "record": {
                      "$ref": "#/components/schemas/created_record"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/contacts/{contact_id}": {
      "get": {
        "operationId": "getContact",
        "summary": "Get contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/include_raw_data"
          }
        ],
        "responses": {
          "200": {
            "description": "Contact",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/contact"
                }
              }
            }
          }
        }
      },
      "patch": {
        "operationId": "updateContact",
        "summary": "Update contact",
        "tags": [
          "Contacts"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "record": {
                    "$ref": "#/components/schemas/create_contact"
                  }
                },
                "required": [
                  "record"
                ]
              },
              "examples": {
                "Example": {
                  "value": {
                    "record": {
                      "id": 1234,
                      "address": {
                        "city": "San Francisco",
                        "country": "USA",
                        "street_1": "525 Brannan St",
                        "street_2": null,
                        "postalCode": "94107",
                        "state": "CA"
                      },
                      "email_addresses": [
                        {
                          "email_address": "hello@supaglue.com",
                          "email_address_type": "workline2"
                        }
                      ],
                      "first_name": "George",
                      "last_name": "Xing",
                      "phone_numbers": [
                        {
                          "phone_number": "+14151234567",
                          "phone_number_type": "mobile"
                        }
                      ],
                      "created_at": "2023-02-27T00:00:00Z"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Contact updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "contact_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/users/{user_id}": {
      "get": {
        "operationId": "getUser",
        "summary": "Get user",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/include_raw_data"
          }
        ],
        "responses": {
          "200": {
            "description": "User",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/user"
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "user_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/mailboxes/{mailbox_id}": {
      "get": {
        "operationId": "getMailbox",
        "summary": "Get mailbox",
        "tags": [
          "Mailboxes"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/include_raw_data"
          }
        ],
        "responses": {
          "200": {
            "description": "Mailbox",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/mailbox"
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "mailbox_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/sequences/{sequence_id}": {
      "get": {
        "operationId": "getSequence",
        "summary": "Get sequence",
        "tags": [
          "Sequences"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/include_raw_data"
          }
        ],
        "responses": {
          "200": {
            "description": "Sequence",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/sequence"
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "sequence_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "0258cbc6-6020-430a-848e-aafacbadf4ae"
          }
        }
      ]
    },
    "/sequence_states": {
      "post": {
        "operationId": "createSequenceState",
        "summary": "Create sequence state",
        "tags": [
          "Sequence States"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "record": {
                    "$ref": "#/components/schemas/create_sequence_state"
                  }
                },
                "required": [
                  "record"
                ]
              },
              "example": {
                "record": {
                  "id": "355843a5-c536-4e82-b497-05160bfb7d78",
                  "state": "active",
                  "mailbox_id": "a7e860b5-cb8b-400b-812d-921fa526140c",
                  "contact_id": "6bdcebc2-f886-4de3-88ed-0b9eb420f7b1",
                  "sequence_id": "45e07817-fd59-4ec8-a727-066d2db27c9b",
                  "created_at": "2023-02-27T00:00:00Z",
                  "updated_at": "2023-02-27T00:00:00Z"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sequence state created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "errors": {
                      "$ref": "#/components/schemas/errors"
                    },
                    "logs": {
                      "$ref": "#/components/schemas/logs"
                    },
                    "record": {
                      "$ref": "#/components/schemas/created_record"
                    },
                    "warnings": {
                      "$ref": "#/components/schemas/warnings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        }
      ]
    },
    "/sequence_states/{sequence_state_id}": {
      "get": {
        "operationId": "getSequenceState",
        "summary": "Get sequence state",
        "tags": [
          "Sequence States"
        ],
        "security": [
          {
            "ApiKeyAuth": []
          }
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/include_raw_data"
          }
        ],
        "responses": {
          "200": {
            "description": "Sequence State",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/sequence_state"
                }
              }
            }
          }
        }
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/x-customer-id"
        },
        {
          "$ref": "#/components/parameters/x-provider-name"
        },
        {
          "name": "sequence_state_id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string",
            "example": "ffb62704-addd-454e-bb86-ed0799703dc6"
          }
        }
      ]
    }
  },
  "tags": [
    {
      "name": "Contacts",
      "description": "The `Contact` Common Model is used to represent a \"contact\" in Engagements."
    },
    {
      "name": "Sequences",
      "description": "The `Sequence` Common Model is used to represent a \"sequence\" in Engagements."
    },
    {
      "name": "Sequence States",
      "description": "The `Sequence State` Common Model is used to represent the state of a contact in a sequence."
    },
    {
      "name": "Users",
      "description": "The `User` Common Model is used to represent a \"user\" in Engagements."
    },
    {
      "name": "Mailboxes",
      "description": "The `Mailbox` Common Model is used to represent email mailbox, used within the application for sending and syncing emails"
    },
    {
      "name": "Passthrough",
      "description": "Passthrough operations to underlying providers."
    }
  ],
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "name": "x-api-key",
        "in": "header",
        "description": "API key to allow developers to access the API"
      }
    },
    "schemas": {
      "contact": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": 54312
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "23e640fe-6105-4a11-a636-3aa6b6c6e762"
          },
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "job_title": {
            "type": "string",
            "nullable": true,
            "example": "CEO"
          },
          "address": {
            "$ref": "#/components/schemas/address"
          },
          "email_addresses": {
            "$ref": "#/components/schemas/email_addresses"
          },
          "phone_numbers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "phone_number": {
                  "type": "string",
                  "nullable": true,
                  "example": "+14151234567"
                },
                "phone_number_type": {
                  "type": "string",
                  "nullable": true,
                  "enum": [
                    "work",
                    "home",
                    "mobile",
                    "other"
                  ]
                }
              },
              "required": [
                "phone_number",
                "phone_number_type"
              ]
            },
            "example": [
              {
                "phone_number": "+14151234567",
                "phone_number_type": "work"
              }
            ]
          },
          "open_count": {
            "type": "number"
          },
          "click_count": {
            "type": "number"
          },
          "reply_count": {
            "type": "number"
          },
          "bounced_count": {
            "type": "number"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "is_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "raw_data": {
            "type": "object",
            "additionalProperties": true
          }
        },
        "required": [
          "id",
          "owner_id",
          "first_name",
          "last_name",
          "job_title",
          "address",
          "email_addresses",
          "phone_numbers",
          "open_count",
          "click_count",
          "reply_count",
          "bounced_count",
          "created_at",
          "updated_at",
          "is_deleted",
          "last_modified_at"
        ]
      },
      "create_contact": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "job_title": {
            "type": "string",
            "nullable": true,
            "example": "CEO"
          },
          "address": {
            "$ref": "#/components/schemas/address"
          },
          "email_addresses": {
            "$ref": "#/components/schemas/email_addresses"
          },
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "9f3e97fd-4d5d-4efc-959d-bbebfac079f5"
          },
          "custom_fields": {
            "$ref": "#/components/schemas/custom_fields"
          }
        }
      },
      "sequence_state": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": 54312
          },
          "state": {
            "type": "string",
            "nullable": true,
            "example": "active"
          },
          "contact_id": {
            "type": "string",
            "nullable": true,
            "example": "c590dc63-8e43-48a4-8154-1fbb00ac936b"
          },
          "mailbox_id": {
            "nullable": true,
            "type": "string",
            "example": "39fd1fe0-094b-4a61-b47f-3e3ac033203d"
          },
          "sequence_id": {
            "nullable": true,
            "type": "string",
            "example": "b854e510-1c40-4ef6-ade4-8eb35f49d331"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "is_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "state",
          "mailbox_id",
          "contact_id",
          "sequence_id",
          "created_at",
          "updated_at",
          "is_deleted",
          "last_modified_at"
        ]
      },
      "create_sequence_state": {
        "type": "object",
        "properties": {
          "contact_id": {
            "type": "string",
            "example": "c590dc63-8e43-48a4-8154-1fbb00ac936b"
          },
          "mailbox_id": {
            "type": "string",
            "example": "39fd1fe0-094b-4a61-b47f-3e3ac033203d"
          },
          "sequence_id": {
            "type": "string",
            "example": "b854e510-1c40-4ef6-ade4-8eb35f49d331"
          }
        },
        "required": [
          "contact_id",
          "mailbox_id",
          "sequence_id"
        ]
      },
      "mailbox": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": 54312
          },
          "email": {
            "type": "string",
            "nullable": true,
            "example": null
          },
          "user_id": {
            "nullable": true,
            "type": "string",
            "example": "39fd1fe0-094b-4a61-b47f-3e3ac033203d"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "is_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "email",
          "user_id",
          "created_at",
          "updated_at",
          "is_deleted",
          "last_modified_at"
        ]
      },
      "user": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": 54312
          },
          "first_name": {
            "type": "string",
            "nullable": true,
            "example": "George"
          },
          "last_name": {
            "type": "string",
            "nullable": true,
            "example": "Xing"
          },
          "email": {
            "type": "string",
            "nullable": true,
            "example": "george@supaglue.com"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "is_deleted": {
            "type": "boolean",
            "example": false
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "first_name",
          "last_name",
          "email",
          "created_at",
          "updated_at",
          "is_deleted",
          "last_modified_at"
        ]
      },
      "sequence": {
        "type": "object",
        "properties": {
          "owner_id": {
            "type": "string",
            "nullable": true,
            "example": "95fe0d29-e8cc-48ac-9afd-e02d8037a597"
          },
          "id": {
            "type": "string",
            "example": 54312
          },
          "is_enabled": {
            "type": "boolean",
            "example": true
          },
          "name": {
            "nullable": true,
            "type": "string"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "num_steps": {
            "type": "number"
          },
          "schedule_count": {
            "type": "number"
          },
          "open_count": {
            "type": "number"
          },
          "opt_out_count": {
            "type": "number"
          },
          "reply_count": {
            "type": "number"
          },
          "click_count": {
            "type": "number"
          },
          "created_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "updated_at": {
            "type": "string",
            "nullable": true,
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          },
          "last_modified_at": {
            "type": "string",
            "format": "date-time",
            "example": "2022-02-27T00:00:00Z"
          }
        },
        "required": [
          "id",
          "is_enabled",
          "name",
          "tags",
          "num_steps",
          "schedule_count",
          "open_count",
          "opt_out_count",
          "reply_count",
          "click_count",
          "created_at",
          "updated_at",
          "last_modified_at"
        ]
      },
      "pagination": {
        "type": "object",
        "properties": {
          "next": {
            "type": "string",
            "nullable": true,
            "example": "eyJpZCI6IjQyNTc5ZjczLTg1MjQtNDU3MC05YjY3LWVjYmQ3MDJjNmIxNCIsInJldmVyc2UiOmZhbHNlfQ=="
          },
          "previous": {
            "type": "string",
            "nullable": true,
            "example": "eyJpZCI6IjBjZDhmYmZkLWU5NmQtNDEwZC05ZjQxLWIwMjU1YjdmNGI4NyIsInJldmVyc2UiOnRydWV9"
          },
          "total_count": {
            "type": "number",
            "example": 100
          }
        }
      },
      "address": {
        "type": "object",
        "nullable": true,
        "properties": {
          "city": {
            "type": "string",
            "nullable": true,
            "example": "San Francisco"
          },
          "country": {
            "type": "string",
            "nullable": true,
            "example": "USA"
          },
          "postal_code": {
            "type": "string",
            "nullable": true,
            "example": "94107"
          },
          "state": {
            "type": "string",
            "nullable": true,
            "example": "CA"
          },
          "street_1": {
            "type": "string",
            "nullable": true,
            "example": "525 Brannan"
          },
          "street_2": {
            "type": "string",
            "nullable": true,
            "example": null
          }
        },
        "required": [
          "city",
          "country",
          "postal_code",
          "state",
          "street_1",
          "street_2"
        ],
        "example": [
          {
            "city": "San Francisco",
            "country": "US",
            "postal_code": "94107",
            "state": "CA",
            "street_1": "525 Brannan",
            "street_2": null
          }
        ]
      },
      "email_addresses": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "email_address": {
              "type": "string",
              "example": "hello@supaglue.com"
            },
            "email_address_type": {
              "type": "string",
              "nullable": true,
              "enum": [
                "personal",
                "work"
              ]
            }
          },
          "required": [
            "email_address",
            "email_address_type"
          ]
        },
        "example": [
          {
            "email_address": "hello@supaglue.com",
            "email_address_type": "work"
          }
        ]
      },
      "custom_fields": {
        "type": "object",
        "additionalProperties": true,
        "description": "Custom properties to be inserted that are not covered by the common model. Object keys must match exactly to the corresponding provider API."
      },
      "created_record": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          }
        },
        "required": [
          "id"
        ]
      },
      "logs": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "dashboard_view": {
              "type": "string",
              "example": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832"
            },
            "log_id": {
              "type": "string",
              "example": "99433219-8017-4acd-bb3c-ceb23d663832"
            },
            "log_summary": {
              "type": "object",
              "properties": {
                "method": {
                  "type": "string",
                  "example": "POST"
                },
                "status_code": {
                  "type": "number",
                  "example": 200
                },
                "url": {
                  "type": "string",
                  "example": "https://harvest.greenhouse.io/v1/candidates/"
                }
              }
            }
          }
        },
        "example": [
          {
            "dashboard_view": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832",
            "log_id": "99433219-8017-4acd-bb3c-ceb23d663832",
            "log_summary": {
              "method": "POST",
              "status_code": 200,
              "url": "https://harvest.greenhouse.io/v1/candidates/"
            }
          },
          {
            "dashboard_view": "https://api.supaglue.com/logs/99433219-8017-4acd-bb3c-ceb23d663832",
            "log_id": "99433219-8017-4acd-bb3c-ceb23d663832",
            "log_summary": {
              "method": "POST",
              "status_code": 200,
              "url": "https://harvest.greenhouse.io/v1/candidates/"
            }
          }
        ]
      },
      "errors": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "detail": {
              "type": "string",
              "example": "name is a required field on model."
            },
            "problem_type": {
              "type": "string",
              "example": "MISSING_REQUIRED_FIELD"
            },
            "source": {
              "type": "object",
              "properties": {
                "pointer": {
                  "type": "string",
                  "example": "irure consectetur"
                }
              }
            },
            "title": {
              "type": "string",
              "example": "Missing Required Field"
            }
          },
          "example": [
            {
              "detail": "name is a required field on model.",
              "problem_type": "MISSING_REQUIRED_FIELD",
              "source": {
                "pointer": "irure consectetur"
              },
              "title": "Missing Required Field"
            },
            {
              "detail": "name is a required field on model.",
              "problem_type": "MISSING_REQUIRED_FIELD",
              "source": {
                "pointer": "et"
              },
              "title": "Missing Required Field"
            }
          ]
        }
      },
      "warnings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "detail": {
              "type": "string",
              "example": "An unrecognized field, age, was passed in with request data."
            },
            "problem_type": {
              "type": "string",
              "example": "UNRECOGNIZED_FIELD"
            },
            "source": {
              "type": "object",
              "properties": {
                "pointer": {
                  "type": "string",
                  "example": "Lorem ipsum"
                }
              }
            },
            "title": {
              "type": "string",
              "example": "Unrecognized Field"
            }
          }
        },
        "example": [
          {
            "detail": "An unrecognized field, age, was passed in with request data.",
            "problem_type": "UNRECOGNIZED_FIELD",
            "source": {
              "pointer": "Lorem ipsum"
            },
            "title": "Unrecognized Field"
          },
          {
            "detail": "An unrecognized field, age, was passed in with request data.",
            "problem_type": "UNRECOGNIZED_FIELD",
            "source": {
              "pointer": "in"
            },
            "title": "Unrecognized Field"
          }
        ]
      }
    },
    "parameters": {
      "include_deleted_data": {
        "name": "include_deleted_data",
        "in": "query",
        "schema": {
          "type": "boolean",
          "example": true
        },
        "description": "Whether to include data that was deleted in providers."
      },
      "include_raw_data": {
        "name": "include_raw_data",
        "in": "query",
        "schema": {
          "type": "boolean",
          "example": true
        },
        "description": "Whether to include raw data fetched from the 3rd party provider."
      },
      "created_after": {
        "name": "created_after",
        "in": "query",
        "schema": {
          "type": "string",
          "format": "date-time",
          "example": "2023-02-23T00:00:00.000Z"
        },
        "description": "If provided, will only return objects created after this datetime"
      },
      "created_before": {
        "name": "created_before",
        "in": "query",
        "schema": {
          "type": "string",
          "format": "date-time",
          "example": "2023-02-23T00:00:00.000Z"
        },
        "description": "If provided, will only return objects created before this datetime"
      },
      "modified_after": {
        "name": "modified_after",
        "in": "query",
        "schema": {
          "type": "string",
          "format": "date-time",
          "example": "2023-02-23T00:00:00.000Z"
        },
        "description": "If provided, will only return objects modified after this datetime"
      },
      "modified_before": {
        "name": "modified_before",
        "in": "query",
        "schema": {
          "type": "string",
          "format": "date-time",
          "example": "2023-02-23T00:00:00.000Z"
        },
        "description": "If provided, will only return objects modified before this datetime"
      },
      "cursor": {
        "name": "cursor",
        "in": "query",
        "schema": {
          "type": "string",
          "example": "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw"
        },
        "description": "The pagination cursor value"
      },
      "page_size": {
        "name": "page_size",
        "in": "query",
        "schema": {
          "type": "string",
          "example": "3804695"
        },
        "description": "Number of results to return per page"
      },
      "x-customer-id": {
        "name": "x-customer-id",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "my-customer-1"
        },
        "description": "The customer ID that uniquely identifies the customer in your application",
        "required": true
      },
      "x-provider-name": {
        "name": "x-provider-name",
        "in": "header",
        "schema": {
          "type": "string",
          "example": "outreach"
        },
        "description": "The provider name",
        "required": true
      }
    }
  }
}